// Generated by CoffeeScript 1.6.3
(function() {
  var analyzeScHelpPage, flexkbd, forecast, optionsTabId, preSendKeyEvent, scHelp, scHelpPageUrl, scHelpSect, scrapeHelp, sendKeyEventToDom, sendMessage, setConfigPlugin, xhr;

  window.fk = {};

  flexkbd = document.getElementById("flexkbd");

  sendMessage = function(message) {
    return chrome.tabs.query({
      active: true
    }, function(tabs) {
      return chrome.tabs.sendMessage(tabs[0].id, message);
    });
  };

  optionsTabId = null;

  chrome.tabs.onActivated.addListener(function(activeInfo) {
    return chrome.tabs.get(activeInfo.tabId, function(tab) {
      if (tab.url.indexOf(chrome.extension.getURL("")) === 0) {
        flexkbd.StartConfigMode();
        return optionsTabId = activeInfo.tabId;
      } else {
        if (optionsTabId) {
          chrome.tabs.sendMessage(optionsTabId, {
            action: "saveConfig"
          });
          return optionsTabId = null;
        }
      }
    });
  });

  chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
    if (tab.url.indexOf(chrome.extension.getURL("")) === 0 && (changeInfo.status = "complete")) {
      return flexkbd.StartConfigMode();
    }
  });

  sendKeyEventToDom = function(keyEvent, tabId) {
    var keyIdentifier, keyIdentifiers, keys, local, modifiers, scanCode, shift;
    local = fk.getConfig();
    keys = fk.getKeyCodes()[local.config.kbdtype].keys;
    modifiers = parseInt(keyEvent.substring(0, 2), 16);
    scanCode = keyEvent.substring(2);
    keyIdentifiers = keys[scanCode];
    if (shift = (modifiers & 4) !== 0) {
      keyIdentifier = keyIdentifiers[1] || keyIdentifiers[0];
    } else {
      keyIdentifier = keyIdentifiers[0];
    }
    return chrome.tabs.sendMessage(tabId, {
      action: "keyEvent",
      keyIdentifier: keyIdentifier,
      ctrl: (modifiers & 1) !== 0,
      alt: (modifiers & 2) !== 0,
      shift: shift,
      meta: (modifiers & 8) !== 0
    });
  };

  preSendKeyEvent = function(keyEvent) {
    return chrome.tabs.query({
      active: true
    }, function(tabs) {
      var tabId;
      tabId = tabs[0].id;
      return chrome.tabs.sendMessage(tabId, {
        action: "askAlive"
      }, function(resp) {
        if (resp === "hello") {
          return sendKeyEventToDom(keyEvent, tabId);
        } else {
          return chrome.tabs.executeScript(tabId, {
            file: "kbdagent.js",
            allFrames: true
          }, function(resp) {
            return sendKeyEventToDom(keyEvent, tabId);
          });
        }
      });
    });
  };

  setConfigPlugin = function(keyConfigSet) {
    var sendData;
    sendData = [];
    if (keyConfigSet) {
      keyConfigSet.forEach(function(item) {
        if (item.proxy) {
          return sendData.push(item.proxy + ";" + item.origin + ";" + item.mode);
        }
      });
      return flexkbd.SetKeyConfig(sendData.join("|"));
    }
  };

  fk.saveConfig = function(saveData) {
    localStorage.flexkbd = JSON.stringify(saveData);
    return setConfigPlugin(saveData.keyConfigSet);
  };

  fk.getKeyCodes = function() {
    return {
      JP: {
        keys: keysJP,
        name: "JP 109 Keyboard"
      },
      US: {
        keys: keysUS,
        name: "US 104 Keyboard"
      }
    };
  };

  fk.getScHelp = function() {
    return scHelp;
  };

  fk.getScHelpSect = function() {
    return scHelpSect;
  };

  fk.getConfig = function() {
    return JSON.parse(localStorage.flexkbd || null) || {
      config: {
        kbdtype: "JP"
      }
    };
  };

  window.pluginEvent = function(action, value) {
    switch (action) {
      case "log":
        return console.log(value);
      case "configKeyEvent":
        return sendMessage({
          action: "kbdEvent",
          value: value
        });
      case "sendToDom":
        return preSendKeyEvent(value);
    }
  };

  setConfigPlugin(fk.getConfig().keyConfigSet);

  scHelp = {};

  scHelpSect = {};

  scHelpPageUrl = "https://support.google.com/chrome/answer/157179?hl=";

  scrapeHelp = function(lang, sectInit, elTab) {
    var targets;
    targets = $(elTab).find("tr:has(td:first-child:has(strong))");
    return $.each(targets, function(i, elem) {
      var content;
      content = elem.cells[1].textContent.replace(/^\s+|\s$/g, "");
      return Array.prototype.forEach.call(elem.childNodes[1].getElementsByTagName("strong"), function(strong) {
        var scKey, _ref;
        scKey = strong.textContent.toUpperCase().replace(/\s/g, "");
        scKey = scKey.replace("PGUP", "PAGEUP").replace("PGDOWN", "PAGEDOWN").replace(/DEL$/, "DELETE").replace(/INS$/, "INSERT");
        if (!((_ref = scHelp[scKey]) != null ? _ref[lang] : void 0)) {
          if (!scHelp[scKey]) {
            scHelp[scKey] = {};
          }
          scHelp[scKey][lang] = [];
        }
        return scHelp[scKey][lang].push(sectInit + "^" + content);
      });
    });
  };

  analyzeScHelpPage = function(resp, lang) {
    var doc, mainSection, sectInit;
    doc = $(resp);
    mainSection = doc.find("div.main-section");
    sectInit = "";
    return Array.prototype.forEach.call(mainSection[0].children, function(el) {
      switch (el.tagName) {
        case "H3":
          switch (el.textContent) {
            case "Tab and window shortcuts":
            case "タブとウィンドウのショートカット":
              sectInit = "T";
              break;
            case "Google Chrome feature shortcuts":
            case "Google Chrome 機能のショートカット":
              sectInit = "C";
              break;
            case "Address bar shortcuts":
            case "アドレスバーのショートカット":
              sectInit = "A";
              break;
            case "Webpage shortcuts":
            case "ウェブページのショートカット":
              sectInit = "W";
              break;
            case "Text shortcuts":
            case "テキストのショートカット":
              sectInit = "Tx";
          }
          return scHelpSect[sectInit] = el.textContent;
        case "TABLE":
          return scrapeHelp(lang, sectInit, el);
      }
    });
  };

  xhr = new XMLHttpRequest();

  forecast = function(lang) {
    var dfd;
    xhr.onreadystatechange = function() {
      if (xhr.readyState === 4 && xhr.status === 200) {
        analyzeScHelpPage(xhr.responseText, lang);
        return dfd.resolve();
      }
    };
    xhr.open("GET", scHelpPageUrl + lang, true);
    xhr.send();
    return (dfd = $.Deferred()).promise();
  };

  forecast("ja").done(function() {
    return forecast("en");
  });

}).call(this);
