// Generated by CoffeeScript 1.6.3
(function() {
  var getMD, iframe, mdToHtml;

  mdToHtml = function(md, iframe) {
    var converter, hash;
    iframe.setAttribute("style", "display:none;");
    document.body.setAttribute("style", "overflow:auto;margin:8px;");
    converter = new Showdown.converter();
    document.getElementById("content").innerHTML = converter.makeHtml(md);
    if (hash = document.location.hash) {
      document.location = hash;
    }
    Array.prototype.forEach.call(document.getElementsByTagName("pre"), function(pre) {
      return pre.className = "prettyprint";
    });
    return prettyPrint();
  };

  getMD = function(iframe) {
    var md, _ref;
    if (md = (_ref = iframe.contentDocument.querySelector("pre")) != null ? _ref.textContent : void 0) {
      mdToHtml(md, iframe);
      return true;
    } else {
      return false;
    }
  };

  iframe = document.getElementById("mdloader");

  if (!getMD(iframe)) {
    iframe.addEventListener("load", function() {
      return getMD(this);
    });
  }

}).call(this);
