// Generated by CoffeeScript 1.6.3
(function() {
  window.scdReadyKbdAgent = true;

  if (!window.scdReadyJQuery) {
    chrome.runtime.onMessage.addListener(function(req, sender, sendResponse) {
      switch (req.action) {
        case "askAlive":
          return sendResponse("hello");
        case "askJQuery":
          if (window.scdReadyJQuery) {
            return sendResponse("hello");
          } else {
            return sendResponse("no");
          }
          break;
        default:
          return sendResponse("no");
      }
    });
  }

  document.addEventListener("keydown", (function(event) {
    var _ref;
    if (event.ctrlKey || event.altKey || event.metaKey || (/F\d/.test(event.keyIdentifier))) {
      return;
    }
    if (((_ref = event.target.tagName) === "TEXTAREA" || _ref === "INPUT" || _ref === "SELECT") || event.target.contentEditable && (event.target.contentEditable === "true" || event.target.contentEditable === "plaintext-only")) {
      return;
    }
    return chrome.runtime.sendMessage({
      action: "clientOnKeyDown",
      value1: event.keyIdentifier,
      value2: event.shiftKey
    }, function(resp) {});
  }), false);

}).call(this);
