// Generated by CoffeeScript 1.6.3
(function() {
  var showCopyHistory, tmplCopyHist, triggerKeyEvent;

  triggerKeyEvent = function(keyIdentifier, ctrlKey, altKey, shiftKey, metaKey) {
    var kbdEvent, opt;
    opt = {
      canBubble: true,
      cancelable: false,
      view: document.defaultView,
      keyLocation: 0x00,
      altGraphKey: false
    };
    kbdEvent = document.createEvent("KeyboardEvent");
    kbdEvent.initKeyboardEvent("keydown", opt.canBubble, opt.cancelable, opt.view, keyIdentifier, opt.keyLocation, ctrlKey, altKey, shiftKey, metaKey, opt.altGraphKey);
    console.log(kbdEvent);
    return document.dispatchEvent(kbdEvent);
  };

  tmplCopyHist = "<div class=\"frame\">\n</div>";

  showCopyHistory = function(history) {
    if (!(window === parent && window === window.top)) {

    }
  };

  chrome.runtime.onMessage.addListener(function(req, sender, sendResponse) {
    var range, selection, _ref;
    switch (req.action) {
      case "askAlive":
        sendResponse("hello");
        break;
      case "keyEvent":
        triggerKeyEvent(req.keyIdentifier, req.ctrl, req.alt, req.shift, req.meta);
        break;
      case "copyText":
        selection = "";
        if (((_ref = (range = window.getSelection())) != null ? _ref.type : void 0) === "Range") {
          selection = range.getRangeAt(0).toString();
          sendResponse(selection);
        }
        break;
      case "showCopyHistory":
        showCopyHistory(req.history);
    }
    return true;
  });

}).call(this);
