// Generated by CoffeeScript 1.6.3
(function() {
  var $, BookmarkOptionsView, BookmarksView, CommandOptionsView, CommandsView, Config, CtxMenuFolder, CtxMenuFolderSet, CtxMenuGetterView, CtxMenuManagerView, CtxMenuOptionsView, EditableBaseView, ExplorerBaseView, HeaderView, KeyConfig, KeyConfigSet, KeyConfigSetView, KeyConfigView, PopupBaseView, WebFontConfig, andy, bmOpenMode, bookmarksView, catnames, commandOptionsView, commandsDisp, commandsView, ctxMenuManagerView, ctxMenuOptionsView, decodeKbdEvent, defaultSleep, endEdit, escape, gMaxItems, getUuid, headerView, keyCodes, keyConfigSetView, keys, lastFocused, loading, marginBottom, modeDisp, modifierInits, modifierKeys, resizeTimer, scHelp, scHelpSect, startEdit, tmplCtxMenus, transKbdEvent, windowOnResize, _ref, _ref1, _ref2, _ref3,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  headerView = null;

  keyConfigSetView = null;

  commandsView = null;

  bookmarksView = null;

  commandOptionsView = null;

  ctxMenuOptionsView = null;

  ctxMenuManagerView = null;

  PopupBaseView = Backbone.View.extend({
    initialize: function(options) {
      return keyConfigSetView.on("showPopup", this.onShowPopup, this);
    },
    events: {
      "submit form": "onSubmitForm",
      "click  .icon-remove": "onClickIconRemove"
    },
    render: function() {},
    onSubmitForm: function() {},
    onShowPopup: function(name, model, options) {
      var modelId, order, parentId, shortcut,
        _this = this;
      if (name !== this.name) {
        return false;
      }
      this.options = options;
      if (this.model = model) {
        order = "";
        if (/^C/.test(modelId = model.get("new"))) {
          shortcut = decodeKbdEvent(parentId = model.get("parentId"));
          $.each(model.collection.where({
            parentId: parentId
          }), function(i, model) {
            if (model.id === modelId) {
              order = "-#" + (i + 1);
              return false;
            }
          });
        } else {
          shortcut = decodeKbdEvent(modelId);
        }
        this.$(".shortcut").html(_.map(shortcut.split(" + "), function(s) {
          return "<span>" + s + "</span>";
        }).join("+") + order);
        model.trigger("showPopup", true);
      }
      this.render();
      this.$el.show().draggable({
        cursor: "move",
        delay: 200,
        cancel: "input,textarea,button,select,option,.bookmarkPanel,span.contexts,span.menuCaption,span.title,div.CodeMirror",
        stop: function() {
          return _this.onStopDrag();
        }
      });
      this.el.style.pixelLeft = Math.round((window.innerWidth - this.el.offsetWidth) / 2);
      this.el.style.pixelTop = Math.round((window.innerHeight - this.el.offsetHeight) / 2);
      this.$(".caption").focus();
      $(".backscreen").show();
      return true;
    },
    onStopDrag: function() {},
    onClickIconRemove: function() {
      return this.hidePopup();
    },
    hidePopup: function() {
      var _ref;
      $(".backscreen").hide();
      this.$el.hide();
      return (_ref = this.model) != null ? _ref.trigger("showPopup", false) : void 0;
    },
    tmplHelp: _.template("<a href=\"helpview.html#<%=name%>\" target=\"helpview\" class=\"help\" title=\"help\">\n  <i class=\"icon-question-sign\" title=\"Help\"></i>\n</a>")
  });

  EditableBaseView = (function(_super) {
    __extends(EditableBaseView, _super);

    function EditableBaseView() {
      _ref = EditableBaseView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    EditableBaseView.prototype.onShowPopup = function(name, model, options) {
      if (!EditableBaseView.__super__.onShowPopup.call(this, name, model, options)) {
        return false;
      }
      startEdit();
      return true;
    };

    EditableBaseView.prototype.hidePopup = function() {
      endEdit();
      return EditableBaseView.__super__.hidePopup.call(this);
    };

    return EditableBaseView;

  })(PopupBaseView);

  ExplorerBaseView = (function(_super) {
    __extends(ExplorerBaseView, _super);

    ExplorerBaseView.prototype.events = _.extend({
      "click .expand-icon": "onClickExpandIcon",
      "click .expandAll": "onClickExpandAll"
    }, PopupBaseView.prototype.events);

    function ExplorerBaseView(options) {
      var ctx;
      ExplorerBaseView.__super__.constructor.call(this, options);
      ctx = document.getCSSCanvasContext("2d", "triangle", 10, 6);
      ctx.translate(.5, .5);
      ctx.fillStyle = "#000000";
      ctx.beginPath();
      ctx.moveTo(8, 0);
      ctx.lineTo(8, .5);
      ctx.lineTo(8 / 2 - .5, 8 / 2 + .5);
      ctx.lineTo(0, .5);
      ctx.lineTo(0, 0);
      ctx.closePath();
      ctx.fill();
      ctx.stroke();
      this.$(".result_outer").niceScroll({
        cursorwidth: 12,
        cursorborderradius: 6,
        smoothscroll: true,
        cursoropacitymin: .1,
        cursoropacitymax: .6
      });
      this.elResult$ = this.$(".result");
    }

    ExplorerBaseView.prototype.onShowPopup = function(name, model, options) {
      if (!ExplorerBaseView.__super__.onShowPopup.call(this, name, model, options)) {
        return false;
      }
      this.$(".result_outer").getNiceScroll().show();
      return true;
    };

    ExplorerBaseView.prototype.onStopDrag = function() {
      return this.$(".result_outer").getNiceScroll().resize();
    };

    ExplorerBaseView.prototype.hidePopup = function() {
      this.$(".result_outer").getNiceScroll().hide();
      return ExplorerBaseView.__super__.hidePopup.call(this);
    };

    ExplorerBaseView.prototype.onClickExpandAll = function() {
      if (this.$(".expandAll").is(":checked")) {
        this.$(".folder,.contexts").addClass("opened expanded");
      } else {
        this.$(".folder,.contexts").removeClass("opened expanded");
      }
      return windowOnResize();
    };

    return ExplorerBaseView;

  })(PopupBaseView);

  commandsDisp = {
    createTab: ["tab", "Create new tab"],
    createTabBG: ["tab", "Create new tab in background"],
    moveTabLeft: ["tab", "Move current tab left"],
    moveTabRight: ["tab", "Move current tab right"],
    moveTabFirst: ["tab", "Move current tab to first position"],
    moveTabLast: ["tab", "Move current tab to last position"],
    closeOtherTabs: ["tab", "Close other tabs"],
    closeTabsLeft: ["tab", "Close tabs to the left"],
    closeTabsRight: ["tab", "Close tabs to the right"],
    duplicateTab: ["tab", "Duplicate current tab"],
    pinTab: ["tab", "Pin/Unpin current tab"],
    detachTab: ["tab", "Detach current tab"],
    attachTab: ["tab", "Attach current tab to the next window"],
    switchPrevWin: ["win", "Switch to the previous window"],
    switchNextWin: ["win", "Switch to the next window"],
    closeOtherWins: ["win", "Close other windows"],
    clearCache: ["clr", "Clear the browser's cache"],
    clearCookiesAll: ["clr", "Clear the browser's cookies and site data"],
    clearCookies: ["clr", "Clear all cookies for the current domain"],
    pasteText: ["custom", "Paste fixed text", [], "Clip"],
    insertCSS: [
      "custom", "Inject CSS", [
        {
          value: "allFrames",
          caption: "All frames"
        }
      ], "CSS", ""
    ],
    execJS: [
      "custom", "Inject script", [
        {
          value: "allFrames",
          caption: "All frames"
        }, {
          value: "coffee",
          caption: "CoffeeScript"
        }, {
          value: "jquery",
          caption: "jQuery"
        }, {
          value: "useUtilObj",
          caption: "Use <a href=\"helpview.html#utilobj\" target=\"helpview\">utility object</a>"
        }
      ], "JS"
    ]
  };

  catnames = {
    tab: "Tab commands",
    win: "Window commands",
    clr: "Browsing data commands",
    clip: "Clipboard commands",
    custom: "Other"
  };

  CommandOptionsView = (function(_super) {
    __extends(CommandOptionsView, _super);

    CommandOptionsView.prototype.name = "commandOptions";

    CommandOptionsView.prototype.el = ".commandOptions";

    CommandOptionsView.prototype.events = _.extend({
      "click input[value='coffee']": "onClickChkCoffee",
      "click .tabs a": "onClickSwitchCoffee"
    }, PopupBaseView.prototype.events);

    function CommandOptionsView(options) {
      var _this = this;
      this.editor = CodeMirror.fromTextArea($(".content")[0], {
        mode: "text/javascript",
        theme: "default",
        tabSize: 2,
        indentUnit: 2,
        indentWithTabs: false,
        tabMode: "spaces",
        enterMode: "keep",
        electricChars: false,
        lineNumbers: true,
        firstLineNumber: 1,
        gutter: false,
        fixedGutter: false,
        matchBrackets: true
      });
      $(".CodeMirror-scroll").addClass("result_outer");
      this.editor.on("change", function() {
        return _this.onStopDrag();
      });
      CommandOptionsView.__super__.constructor.call(this, options);
      commandsView.on("showPopup", this.onShowPopup, this);
      this.$(".content_outer").resizable({
        minWidth: 650,
        minHeight: 200
      });
    }

    CommandOptionsView.prototype.render = function() {
      var commandOption,
        _this = this;
      this.$(".command").html(commandsDisp[this.options.name][1]);
      this.$(".caption").val(this.options.caption);
      commandOption = this.$(".inputs").empty();
      commandsDisp[this.options.name][2].forEach(function(option) {
        option.checked = "";
        if (_this.options[option.value]) {
          option.checked = "checked";
        }
        return commandOption.append(_this.tmplOptions(option));
      });
      this.$el.append(this.tmplHelp(this));
      return this.onClickChkCoffee({
        currentTarget: this.$("input[value='coffee']")
      });
    };

    CommandOptionsView.prototype.onShowPopup = function(name, model, options) {
      var container, mode;
      if (name === this.name) {
        this.trigger("getEditerSize", container = {});
        if (container.width) {
          this.$(".content_outer").width(container.width).height(container.height);
        } else {
          this.$(".content_outer").width(700);
        }
      }
      if (!CommandOptionsView.__super__.onShowPopup.call(this, name, model, options)) {
        return;
      }
      startEdit();
      switch (this.options.name) {
        case "insetCSS":
          mode = "text/css";
          break;
        default:
          mode = "text/javascript";
      }
      this.editor.setOption("mode", mode);
      this.editor.setValue(this.options.content || "");
      if (this.options.content) {
        return this.editor.focus();
      } else {
        return this.$(".caption").focus();
      }
    };

    CommandOptionsView.prototype.onSubmitForm = function() {
      var caption, content, options,
        _this = this;
      if ((content = this.$(".content").val()) !== "") {
        options = {};
        $.each(this.$(".inputs input[type='checkbox']"), function(i, option) {
          options[option.value] = option.checked;
        });
        if (!(caption = this.$(".caption").val())) {
          caption = content.split("\n")[0];
        }
        this.model.set({
          "command": _.extend({
            name: this.options.name,
            caption: caption,
            content: content
          }, options)
        }, {
          silent: true
        }).trigger("change:command");
        this.hidePopup();
      }
      return false;
    };

    CommandOptionsView.prototype.onClickChkCoffee = function(event) {
      if ($(event.currentTarget).is(":checked")) {
        return this.$(".tabs").show();
      } else {
        return this.$(".tabs").hide();
      }
    };

    CommandOptionsView.prototype.hidePopup = function() {
      this.trigger("setEditerSize", this.$(".content_outer").width(), this.$(".content_outer").height());
      endEdit();
      return CommandOptionsView.__super__.hidePopup.call(this);
    };

    CommandOptionsView.prototype.tmplOptions = _.template("<label>\n  <input type=\"checkbox\" value=\"<%=value%>\" <%=checked%>> <%=caption%>\n</label><br>");

    return CommandOptionsView;

  })(ExplorerBaseView);

  CommandsView = (function(_super) {
    __extends(CommandsView, _super);

    function CommandsView() {
      _ref1 = CommandsView.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    CommandsView.prototype.name = "command";

    CommandsView.prototype.el = ".commands";

    CommandsView.prototype.render = function() {
      var categories, key, target$;
      target$ = this.$(".commandRadios");
      target$.empty();
      categories = [];
      for (key in commandsDisp) {
        categories.push(commandsDisp[key][0]);
      }
      categories = _.unique(categories);
      categories.forEach(function(cat) {
        return target$.append("<div class=\"cat" + cat + "\"><div class=\"catname\">" + catnames[cat] + "</div>");
      });
      for (key in commandsDisp) {
        target$.find(".cat" + commandsDisp[key][0]).append(this.tmplItem({
          key: key,
          value: commandsDisp[key][1]
        }));
      }
      return this;
    };

    CommandsView.prototype.onShowPopup = function(name, model, options) {
      if (!CommandsView.__super__.onShowPopup.call(this, name, model)) {
        return;
      }
      if (options) {
        this.$(".radioCommand").val([options.name]);
      }
      return this.$el.append(this.tmplHelp(this));
    };

    CommandsView.prototype.onSubmitForm = function() {
      var command;
      if (command = this.$(".radioCommand:checked").val()) {
        this.hidePopup();
        if (commandsDisp[command][2]) {
          this.trigger("showPopup", "commandOptions", this.model, {
            name: command
          });
        } else {
          this.model.set({
            "command": {
              name: command
            }
          }, {
            silent: true
          }).trigger("change:command");
        }
      }
      return false;
    };

    CommandsView.prototype.tmplItem = _.template("<div>\n  <label>\n    <input type=\"radio\" name=\"radioCommand\" class=\"radioCommand\" value=\"<%=key%>\">\n    <%=value%>\n  </label>\n</div>");

    return CommandsView;

  })(PopupBaseView);

  BookmarkOptionsView = (function(_super) {
    __extends(BookmarkOptionsView, _super);

    BookmarkOptionsView.prototype.name = "bookmarkOptions";

    BookmarkOptionsView.prototype.el = ".bookmarkOptions";

    BookmarkOptionsView.prototype.events = _.extend({
      "click input[value='findtab']": "onClickFindTab",
      "change input[name='openmode']:radio": "onChangeOpenmode"
    }, PopupBaseView.prototype.events);

    function BookmarkOptionsView(options) {
      BookmarkOptionsView.__super__.constructor.call(this, options);
      bookmarksView.on("showPopup", this.onShowPopup, this);
    }

    BookmarkOptionsView.prototype.render = function() {
      var elFindtab, findtab;
      BookmarkOptionsView.__super__.render.call(this);
      this.$(".bookmark").css("background-image", "-webkit-image-set(url(chrome://favicon/size/16@1x/" + this.options.url + ") 1x)").text(this.options.title);
      this.$(".url").text(this.options.url);
      this.$(".findStr").val(this.options.findStr || this.options.url);
      this.$("input[value='" + (this.options.openmode || 'current') + "']")[0].checked = true;
      (elFindtab = this.$("input[value='findtab']")[0]).checked = (findtab = this.options.findtab) === void 0 ? true : findtab;
      this.onClickFindTab({
        currentTarget: elFindtab
      });
      return this.$el.append(this.tmplHelp(this));
    };

    BookmarkOptionsView.prototype.onSubmitForm = function() {
      var options,
        _this = this;
      options = {};
      $.each(this.$("form input[type='checkbox']"), function(i, option) {
        options[option.value] = option.checked;
      });
      options.findtab = this.$("input[value='findtab']").is(":checked");
      options.openmode = this.$("input[name='openmode']:checked").attr("value");
      options.findStr = this.$(".findStr").val();
      this.model.set({
        "bookmark": _.extend(this.options, options)
      }, {
        silent: true
      }).trigger("change:bookmark");
      this.hidePopup();
      return false;
    };

    BookmarkOptionsView.prototype.onChangeOpenmode = function(event) {
      var chkFindtab$, openmode;
      openmode = this.$("input[name='openmode']:checked").val();
      chkFindtab$ = this.$("input[value='findtab']");
      if (openmode === "findonly") {
        chkFindtab$.attr("disabled", "disabled")[0].checked = true;
      } else {
        chkFindtab$.removeAttr("disabled");
      }
      return this.onClickFindTab({
        currentTarget: {
          checked: chkFindtab$[0].checked
        }
      });
    };

    BookmarkOptionsView.prototype.onClickFindTab = function(event) {
      if (event.currentTarget.checked) {
        return this.$(".findStr").removeAttr("disabled");
      } else {
        return this.$(".findStr").attr("disabled", "disabled").blur();
      }
    };

    return BookmarkOptionsView;

  })(EditableBaseView);

  BookmarksView = (function(_super) {
    __extends(BookmarksView, _super);

    function BookmarksView() {
      _ref2 = BookmarksView.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    BookmarksView.prototype.name = "bookmark";

    BookmarksView.prototype.el = ".bookmarks";

    BookmarksView.prototype.events = _.extend({
      "click  a": "onClickBookmark",
      "click .title": "onClickFolder",
      "click .expand-icon": "onClickExpandIcon"
    }, ExplorerBaseView.prototype.events);

    BookmarksView.prototype.render = function() {
      var height;
      height = window.innerHeight - 60;
      this.$(".result_outer").height(height - 35);
      this.$el.height(height);
      if (this.$(".result").children().length === 0) {
        this.onSubmitForm();
      }
      return this;
    };

    BookmarksView.prototype.onShowPopup = function(name, model) {
      var target;
      if (!BookmarksView.__super__.onShowPopup.call(this, name, model)) {
        return;
      }
      if ((target = this.$("input.query")).val()) {
        return target.focus();
      }
    };

    BookmarksView.prototype.onSubmitForm = function() {
      var query, state,
        _this = this;
      this.$(".result").empty();
      query = this.$("input.query").focus().val();
      if (query) {
        this.$(".expandAll")[0].checked = true;
      }
      state = this.$(".expandAll").is(":checked") ? "opened expanded" : "";
      chrome.bookmarks.getTree(function(treeNode) {
        var recent;
        treeNode.forEach(function(node) {
          return _this.digBookmarks(node, _this.elResult$, query, 0, state);
        });
        _this.elResult$.append(recent = $(_this.tmplFolder({
          "title": "Recent",
          "state": state,
          "indent": 0
        })));
        recent.find(".title").prepend("<img src=\"images/star.png\">");
        return chrome.bookmarks.getRecent(50, function(treeNode) {
          return treeNode.forEach(function(node) {
            return _this.digBookmarks(node, recent, query, 1, state);
          });
        });
      });
      return false;
    };

    BookmarksView.prototype.digBookmarks = function(node, parent, query, indent, state) {
      var newParent,
        _this = this;
      if (node.title) {
        node.state = state;
        if (node.children) {
          node.indent = indent;
          parent.append(newParent = $(this.tmplFolder(node)));
          parent = newParent;
        } else {
          if (!query || (node.title + " " + node.url).toUpperCase().indexOf(query.toUpperCase()) > -1) {
            node.indent = indent + 1;
            parent.append($(this.tmplLink(node)));
          }
        }
      } else {
        indent--;
      }
      if (node.children) {
        parent.parent().addClass("hasFolder");
        return node.children.forEach(function(child) {
          return _this.digBookmarks(child, parent, query, indent + 1, state);
        });
      }
    };

    BookmarksView.prototype.onClickFolder = function(event) {
      var target$, visible;
      visible = (target$ = $(event.currentTarget).parent()).hasClass("opened");
      if (visible) {
        target$.removeClass("opened expanded");
      } else {
        target$.addClass("opened expanded");
      }
      windowOnResize();
      return event.stopPropagation();
    };

    BookmarksView.prototype.onClickExpandIcon = function(event) {
      var expanded, target$;
      expanded = (target$ = $(event.currentTarget).parent()).hasClass("expanded");
      if (expanded) {
        target$.removeClass("expanded");
      } else {
        target$.addClass("expanded");
      }
      windowOnResize();
      return event.stopPropagation();
    };

    BookmarksView.prototype.onClickBookmark = function(event) {
      var target;
      this.hidePopup();
      target = $(event.currentTarget);
      this.trigger("showPopup", "bookmarkOptions", this.model, {
        title: target.text(),
        url: target.attr("title"),
        bmId: target.attr("data-id")
      });
      return false;
    };

    BookmarksView.prototype.tmplFolder = _.template("<div class=\"folder <%=state%>\" style=\"text-indent:<%=indent%>em\">\n  <span class=\"expand-icon\"></span><span class=\"title\"><%=title%></span>\n</div>");

    BookmarksView.prototype.tmplLink = _.template("<div class=\"link\" style=\"text-indent:<%=indent%>em;\">\n  <a href=\"#\" title=\"<%=url%>\" data-id=\"<%=id%>\" style=\"background-image:-webkit-image-set(url('chrome://favicon/size/16@1x/<%=url%>') 1x);\"><%=title%></a>\n</div>");

    return BookmarksView;

  })(ExplorerBaseView);

  tmplCtxMenus = {
    page: ["Return the page URL", "icon-file-alt"],
    selection: ["Return the selection text", "icon-font"],
    editable: ["Return the page URL or selection text", "icon-edit"],
    link: ["Return the link URL", "icon-link"],
    image: ["Return the image URL", "icon-picture"],
    all: ["Return any of the above", "icon-asterisk"]
  };

  getUuid = function(init) {
    var S4;
    S4 = function() {
      return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
    };
    return init + [S4(), S4()].join("").toUpperCase() + (new Date / 1000 | 0);
  };

  CtxMenuOptionsView = (function(_super) {
    __extends(CtxMenuOptionsView, _super);

    function CtxMenuOptionsView() {
      _ref3 = CtxMenuOptionsView.__super__.constructor.apply(this, arguments);
      return _ref3;
    }

    CtxMenuOptionsView.prototype.name = "ctxMenuOptions";

    CtxMenuOptionsView.prototype.el = ".ctxMenuOptions";

    CtxMenuOptionsView.prototype.events = _.extend({
      "click  .done,.delete": "onClickSubmit",
      "change .selectParent": "onChangeSelectParent",
      "click  .selectParent": "onClickSelectParent",
      "focus  .parentName": "onFocusParentName",
      "blur   .parentName": "onBlurParentName"
    }, PopupBaseView.prototype.events);

    CtxMenuOptionsView.prototype.render = function() {
      var contexts, ctxType, lastParentId, parentId, selectParent$, _ref4, _ref5, _ref6;
      if (this.ctxMenu = this.model.get("ctxMenu")) {
        if (this.ctxMenu.parentId !== "route") {
          this.ctxMenu.contexts = this.collection.get(this.ctxMenu.parentId).get("contexts");
        }
      }
      this.$(".caption").val(((_ref4 = this.ctxMenu) != null ? _ref4.caption : void 0) || this.options.desc);
      this.$el.append(this.tmplHelp(this));
      this.$("input[value='" + ((contexts = (_ref5 = this.ctxMenu) != null ? _ref5.contexts : void 0) || 'page') + "']")[0].checked = true;
      if (this.ctxMenu) {
        this.$(".delete").addClass("orange").removeClass("disabled").removeAttr("disabled");
      } else {
        this.$(".delete").removeClass("orange").addClass("disabled").attr("disabled", "disabled");
      }
      lastParentId = (selectParent$ = this.$(".selectParent")).val();
      ctxType = this.$("input[name='ctxType']:checked").attr("value");
      selectParent$.html(this.tmplParentMenu);
      this.collection.models.forEach(function(model) {
        return selectParent$.append("<option value=\"" + model.id + "\">" + (model.get("title")) + "</option>");
      });
      if (parentId = (_ref6 = this.ctxMenu) != null ? _ref6.parentId : void 0) {
        selectParent$.val(parentId);
      } else if (selectParent$.find("option[value='" + lastParentId + "']").length > 0) {
        selectParent$.val(lastParentId);
      } else {
        selectParent$.val("route");
      }
      return this.$(".parentName").val("").hide();
    };

    CtxMenuOptionsView.prototype.onChangeSelectParent = function(event) {
      if (event.currentTarget.value !== "new") {
        return this.$(".parentName").hide();
      } else {
        return this.$(".parentName").show().focus();
      }
    };

    CtxMenuOptionsView.prototype.onClickSelectParent = function(event) {
      return event.preventDefault();
    };

    CtxMenuOptionsView.prototype.onFocusParentName = function(event) {
      return this.$(".selectParent").addClass("focus");
    };

    CtxMenuOptionsView.prototype.onBlurParentName = function() {
      return this.$(".selectParent").removeClass("focus");
    };

    CtxMenuOptionsView.prototype.onSubmitForm = function() {
      return false;
    };

    CtxMenuOptionsView.prototype.onClickSubmit = function(event) {
      var caption, container, ctxType, dfd, model, parentId, parentName, _ref4, _ref5,
        _this = this;
      if ((parentId = this.$(".selectParent").val()) === "new") {
        if ((parentName = $.trim(this.$(".parentName").val())) === "") {
          return false;
        }
      }
      if ((caption = $.trim(this.$(".caption").val())) === "") {
        return false;
      }
      if (/delete/.test(event != null ? event.currentTarget.className : void 0)) {
        if (!confirm("Are you sure you want to delete this Context Menu?")) {
          return false;
        }
        this.model.unset("ctxMenu");
      } else {
        ctxType = this.$("input[name='ctxType']:checked").attr("value");
        if (parentId === "route") {
          this.model.set("ctxMenu", {
            caption: caption,
            contexts: ctxType,
            parentId: parentId,
            order: (_ref4 = this.ctxMenu) != null ? _ref4.order : void 0
          });
        } else {
          if (parentId === "new") {
            if (model = this.collection.findWhere({
              contexts: ctxType,
              title: parentName
            })) {
              parentId = model.id;
            }
          } else {
            parentName = this.$(".selectParent option[value='" + parentId + "']").text();
          }
          if (!this.collection.findWhere({
            id: parentId,
            contexts: ctxType
          })) {
            this.collection.add({
              id: parentId = getUuid("T"),
              contexts: ctxType,
              title: parentName
            });
          }
          this.model.set("ctxMenu", {
            caption: caption,
            parentId: parentId,
            order: (_ref5 = this.ctxMenu) != null ? _ref5.order : void 0
          });
        }
      }
      this.trigger("getCtxMenues", container = {});
      (_.difference(this.collection.pluck("id"), _.pluck(container.ctxMenus, "parentId"))).forEach(function(id) {
        return _this.collection.remove(_this.collection.get(id));
      });
      (dfd = $.Deferred()).promise();
      this.trigger("remakeCtxMenu", {
        dfd: dfd
      });
      dfd.done(function() {
        return _this.hidePopup();
      });
      return false;
    };

    CtxMenuOptionsView.prototype.tmplParentMenu = "<option value=\"route\">None(Root)</option>\n<option value=\"new\">Create under new parent menu...</option>";

    return CtxMenuOptionsView;

  })(EditableBaseView);

  CtxMenuFolder = Backbone.Model.extend({});

  CtxMenuFolderSet = Backbone.Collection.extend({
    model: CtxMenuFolder
  });

  CtxMenuGetterView = (function(_super) {
    __extends(CtxMenuGetterView, _super);

    CtxMenuGetterView.prototype.el = ".ctxMenusGetter";

    CtxMenuGetterView.prototype.events = _.extend({
      "click .add": "onClickAdd",
      "click .cancel": "onClickCancel"
    }, PopupBaseView.prototype.events);

    function CtxMenuGetterView(options) {
      CtxMenuGetterView.__super__.constructor.call(this, options);
      this.$el.css({
        top: 0,
        right: "30px"
      }).draggable({
        cursor: "move",
        delay: 200,
        cancel: "input,textarea,button,select,option"
      });
    }

    CtxMenuGetterView.prototype.render = function(message) {
      this.$(".message").html(this.tmplMessage(message));
      this.$el.show(200);
      return this;
    };

    CtxMenuGetterView.prototype.hidePopup = function() {
      return this.$el.hide(200);
    };

    CtxMenuGetterView.prototype.onClickAdd = function() {
      this.$el.hide(200);
      return this.trigger("addCtxMenus");
    };

    CtxMenuGetterView.prototype.onClickCancel = function() {
      this.$el.hide(200);
      return this.trigger("addCtxMenus", true);
    };

    CtxMenuGetterView.prototype.tmplMessage = _.template("Add entries to the context menu for <span class=\"ctxmenu-icon\"><i class=\"<%=icon%>\"></i></span><strong><%=contextName%></strong><%=folder%><br>from the functions that you selected.");

    return CtxMenuGetterView;

  })(PopupBaseView);

  CtxMenuManagerView = (function(_super) {
    __extends(CtxMenuManagerView, _super);

    CtxMenuManagerView.prototype.name = "ctxMenuManager";

    CtxMenuManagerView.prototype.el = ".ctxMenuManager";

    CtxMenuManagerView.prototype.events = _.extend({
      "mousedown span[tabindex='0']": "onClickItem",
      "mousedown button,input,a": "onClickClickable",
      "mousedown .newmenu": "onClickNew",
      "mousedown .newfolder": "onClickNewFolder",
      "mousedown .rename": "onClickRen",
      "dblclick  .menuCaption,.title": "onClickRen",
      "keydown   .menuCaption,.title": "onKeydownCaption",
      "mousedown .remove": "onClickRemove",
      "submit .editCaption": "doneEditCaption",
      "blur .editCaption input": "cancelEditCaption",
      "mousedown": "onClickBlank",
      "click .done": "onClickDone"
    }, ExplorerBaseView.prototype.events);

    function CtxMenuManagerView(options) {
      var ctx, i, _i;
      CtxMenuManagerView.__super__.constructor.call(this, options);
      this.ctxMenuGetterView = new CtxMenuGetterView({});
      this.ctxMenuGetterView.on("addCtxMenus", this.onAddCtxMenus, this);
      ctxMenuOptionsView.on("showPopup", this.onShowPopup, this);
      headerView.on("showPopup", this.onShowPopup, this);
      keyConfigSetView.on("addCtxMenu", this.onAddCtxMenu, this);
      ctx = document.getCSSCanvasContext("2d", "empty", 18, 18);
      ctx.strokeStyle = "#CC0000";
      ctx.lineWidth = "2";
      ctx.lineCap = "round";
      ctx.beginPath();
      ctx.moveTo(1, 1);
      ctx.lineTo(17, 17);
      ctx.moveTo(1, 17);
      ctx.lineTo(17, 1);
      ctx.stroke();
      ctx = document.getCSSCanvasContext("2d", "updown", 26, 24);
      ctx.fillStyle = "rgb(122, 122, 160)";
      ctx.lineWidth = "2";
      ctx.lineCap = "round";
      ctx.lineJoin = "round";
      ctx.strokeStyle = "#333333";
      for (i = _i = 0; _i <= 1; i = ++_i) {
        ctx.beginPath();
        ctx.moveTo(1, 5);
        ctx.lineTo(5, 1);
        ctx.lineTo(9, 5);
        ctx.moveTo(5, 1);
        ctx.lineTo(5, 9);
        ctx.stroke();
        ctx.translate(18, 18);
        ctx.rotate(180 * Math.PI / 180);
      }
      this.collection.comparator = function(model) {
        return model.get("order");
      };
    }

    CtxMenuManagerView.prototype.render = function() {
      var height,
        _this = this;
      height = window.innerHeight - 60;
      this.$(".result_outer").height(height - 35);
      this.$el.height(height);
      this.setContextMenu();
      this.setSortable(".folders", ".title,.menuCaption", this.onUpdateFolder);
      this.setSortable(".ctxMenus", ".menuCaption", this.onUpdateMenu);
      $.each(this.$(".editButtons button"), function(i, el) {
        return _this.disableButton(_.map(document.querySelectorAll(".editButtons button"), function(el) {
          return el.className.match(/^(\w+)\s/)[1];
        }));
      });
      this.$el.append(this.tmplHelp(this));
      return this;
    };

    CtxMenuManagerView.prototype.onShowPopup = function(name, model, options) {
      if (!CtxMenuManagerView.__super__.onShowPopup.call(this, name, model, options)) {
        return false;
      }
      return startEdit();
    };

    CtxMenuManagerView.prototype.hidePopup = function() {
      endEdit();
      return CtxMenuManagerView.__super__.hidePopup.call(this);
    };

    CtxMenuManagerView.prototype.onSubmitForm = function() {
      return false;
    };

    CtxMenuManagerView.prototype.setSortable = function(selector, handle, fnDoneUpdate) {
      var _this = this;
      return this.$(selector).sortable({
        scroll: true,
        handle: handle,
        connectWith: selector,
        placeholder: "ui-placeholder",
        delay: 200,
        update: function(event, ui) {
          return fnDoneUpdate(event, ui, _this);
        },
        start: function(event, ui) {
          return _this.onStartSort(event, ui);
        },
        stop: function(event, ui) {
          return _this.onStopSort(event, ui, _this);
        }
      });
    };

    CtxMenuManagerView.prototype.setFolderDroppable = function(target$) {
      var that;
      that = this;
      return target$.droppable({
        accept: ".ctxMenuItem.route",
        tolerance: "pointer",
        hoverClass: "drop-folder-hover",
        over: function() {
          return $(".folders .ui-placeholder").hide();
        },
        out: function() {
          return $(".folders .ui-placeholder").show();
        },
        drop: function(event, ui) {
          var ctxMenu$;
          ctxMenu$ = $(this).find(".ctxMenus");
          return ui.draggable.hide("fast", function() {
            return that.onUpdateMenu(null, {
              item: $(this).appendTo(ctxMenu$).removeClass("route").show().find("span[tabindex='0']").focus()
            }, that);
          });
        }
      });
    };

    CtxMenuManagerView.prototype.onUpdateFolder = function(event, ui, view) {
      var folders$, ref;
      if (ui && _.filter(ui.item.parent().find(".title"), function(title) {
        var _ref4;
        return title.textContent === ((_ref4 = ui.item.prevInfo) != null ? _ref4.text : void 0);
      }).length > 1) {
        alert("A folder with the name '" + ui.item.prevInfo.text + "' already exists.");
        folders$ = view.$(".folders." + ui.item.prevInfo.contexts);
        ref = folders$.children().eq(ui.item.prevInfo.order).get(0) || null;
        folders$[0].insertBefore(ui.item[0], ref);
        return;
      }
      $.each(view.$(".folders"), function(i, folders) {
        if ((folders$ = $(folders)).find(".folder,.ctxMenuItem").length > 0) {
          return folders$.parents(".contexts").addClass("hasFolder");
        } else {
          return folders$.parents(".contexts").removeClass("hasFolder");
        }
      });
      if (ui) {
        return ui.item.focus();
      }
    };

    CtxMenuManagerView.prototype.onUpdateMenu = function(event, ui, view) {
      $.each(view.$(".ctxMenus"), function(i, menuItem) {
        var menuItem$;
        if ((menuItem$ = $(menuItem)).find(".ctxMenuItem,.dummy").length === 0) {
          return menuItem$.parents(".folder").removeClass("hasFolder");
        }
      });
      if (ui) {
        ui.item.parents(".folder").addClass("hasFolder");
        return ui.item.focus();
      }
    };

    CtxMenuManagerView.prototype.onGetCtxMenuContexts = function(container) {
      return container.contexts = this.collection.get(container.parentId).get("contexts");
    };

    CtxMenuManagerView.prototype.onClickDone = function() {
      var dfd, newCtxMenu,
        _this = this;
      newCtxMenu = [];
      this.collection.reset();
      $.each(this.$(".ctxMenuItem"), function(i, el) {
        var contexts, menu$, message, _ref4;
        menu$ = $(el);
        message = {
          id: el.id
        };
        message.caption = menu$.find(".menuCaption").text();
        message.order = i + 1;
        message.parentId = ((_ref4 = menu$.parents(".folder").get(0)) != null ? _ref4.id : void 0) || "route";
        contexts = menu$.parents(".folders")[0].className.match(/folders\s(\w+)/)[1];
        if (message.parentId === "route") {
          message.contexts = contexts;
        } else {
          if (!_this.collection.findWhere({
            id: message.parentId,
            contexts: contexts
          })) {
            _this.collection.add({
              id: message.parentId,
              contexts: contexts,
              title: _this.$("#" + message.parentId + " .title").text()
            });
          }
        }
        return newCtxMenu.push(message);
      });
      this.trigger("setCtxMenus", newCtxMenu);
      (dfd = $.Deferred()).promise();
      this.trigger("remakeCtxMenu", {
        dfd: dfd
      });
      dfd.done(function() {
        return _this.hidePopup();
      });
      return false;
    };

    CtxMenuManagerView.prototype.onClickBlank = function() {};

    CtxMenuManagerView.prototype.onClickClickable = function(event) {
      return event.stopPropagation();
    };

    CtxMenuManagerView.prototype.onClickNew = function(event) {
      var className, contexts$, entried, target$, _ref4;
      if (!/contexts|title/.test((_ref4 = (target$ = $(document.activeElement)).get(0)) != null ? _ref4.className : void 0)) {
        return;
      }
      this.activeFolder = {};
      if (target$.hasClass("contexts")) {
        this.activeFolder.folder = "";
        contexts$ = target$;
        this.activeFolder.parentId = "route";
        this.activeFolder.contexts = (className = target$.parent()[0].className).match(/droppable\s(\w+)/)[1];
        this.activeFolder.selector = "." + className.replace(/\s/g, ".") + " .contexts";
      } else {
        this.activeFolder.folder = " in the folder '<strong>" + (target$.text()) + "</strong>'";
        contexts$ = target$.parents("div.contexts").find("span.contexts");
        this.activeFolder.parentId = target$.parent()[0].id;
        this.activeFolder.selector = "#" + this.activeFolder.parentId + " .title";
      }
      this.activeFolder.icon = contexts$.find("i")[0].className;
      this.activeFolder.contextName = contexts$.text();
      this.ctxMenuGetterView.render(this.activeFolder);
      entried = _.map(this.$(".ctxMenuItem"), function(el) {
        return el.id;
      });
      this.trigger("enterCtxMenuSelMode", entried);
      this.$(".result_outer").getNiceScroll().hide();
      this.$el.hide();
      return $(".backscreen").hide();
    };

    CtxMenuManagerView.prototype.onAddCtxMenu = function(ctxMenu) {
      this.setContextMenuItem(_.extend(ctxMenu, this.activeFolder));
      this.$("#" + ctxMenu.id).hide().show(300);
      this.setSortable(".ctxMenus", ".menuCaption", this.onUpdateMenu);
      return this.$(".folders").sortable("refresh");
    };

    CtxMenuManagerView.prototype.onAddCtxMenus = function(cancel) {
      this.trigger("leaveCtxMenuSelMode", cancel);
      this.$el.show();
      this.$(".result_outer").getNiceScroll().show();
      $(".backscreen").show();
      this.$(this.activeFolder.selector).focus();
      if (cancel) {
        return;
      }
      this.trigger("triggerEventSelected");
      this.onUpdateMenu(null, null, this);
      this.onUpdateFolder(null, null, this);
      return this.$(this.activeFolder.selector).focus();
    };

    CtxMenuManagerView.prototype.onClickNewFolder = function(event) {
      var folders$, newFolder$, target$;
      if (!(target$ = $(document.activeElement)).hasClass("contexts")) {
        return;
      }
      folders$ = target$.parents(".contexts").find(".folders");
      (newFolder$ = $(this.tmplFolder({
        id: getUuid("T"),
        title: ""
      })).appendTo(folders$)).find(".title").focus();
      this.setSortable(".ctxMenus", ".menuCaption", this.onUpdateMenu);
      this.$(".folders").sortable("refresh");
      this.setFolderDroppable(newFolder$);
      this.enableButton(["rename", "remove", "newmenu"]);
      this.disableButton(["newfolder"]);
      return this.onClickRen(event);
    };

    CtxMenuManagerView.prototype.onKeydownCaption = function(event) {
      if (event.originalEvent.keyIdentifier === "F2") {
        return this.onClickRen(event);
      }
    };

    CtxMenuManagerView.prototype.onClickRen = function(event) {
      var editer$, target$;
      if (!/title|menuCaption/.test((target$ = $(document.activeElement))[0].className)) {
        return;
      }
      editer$ = target$.hide().parent().find(".editCaption input:first").show();
      editer$.val(target$.text()).focus();
      return event.preventDefault();
    };

    CtxMenuManagerView.prototype.escapeAmp = function(text) {
      return text.replace(/&&/g, "^ampersand^").replace(/&/g, "").replace(/^ampersand^/g, "");
    };

    CtxMenuManagerView.prototype.doneEditCaption = function(event) {
      var editer$, folder$, notExists, value;
      if (value = $.trim((editer$ = $(event.currentTarget).find("> input")).val())) {
        if ((folder$ = editer$.parent().parent()).hasClass("folder")) {
          notExists = true;
          $.each(folder$.parent().find(".title"), function(i, title) {
            if (folder$[0] !== title.parentNode && title.textContent === value) {
              $("#tiptip_content").text("Folder '" + value + "' already exists.");
              editer$.tipTip();
              return notExists = false;
            }
          });
          if (!notExists) {
            return false;
          }
        }
      } else {
        editer$.blur();
        return false;
      }
      editer$.hide().parents("div:first").find("> .title,> .menuCaption").show().text(value).focus();
      return false;
    };

    CtxMenuManagerView.prototype.cancelEditCaption = function(event) {
      var target$;
      if (!(target$ = $(event.currentTarget).hide().parents("div:first").find(".title,.menuCaption").show()).text()) {
        return target$.parents(".folder").remove();
      }
    };

    CtxMenuManagerView.prototype.onClickRemove = function(event) {
      var active$;
      if (!/title|menuCaption/.test((active$ = $(document.activeElement))[0].className)) {
        return;
      }
      active$.parent().remove();
      this.onUpdateMenu(null, null, this);
      return this.onUpdateFolder(null, null, this);
    };

    CtxMenuManagerView.prototype.enableButton = function(buttonClasses) {
      return buttonClasses.forEach(function(className) {
        return this.$("button." + className).removeClass("disabled").removeAttr("disabled");
      });
    };

    CtxMenuManagerView.prototype.disableButton = function(buttonClasses) {
      return buttonClasses.forEach(function(className) {
        return this.$("button." + className).addClass("disabled").attr("disabled", "disabled");
      });
    };

    CtxMenuManagerView.prototype.onClickItem = function(event) {
      switch (event.currentTarget.className) {
        case "contexts":
          this.enableButton(["newmenu", "newfolder"]);
          this.disableButton(["rename", "remove"]);
          break;
        case "title":
          this.enableButton(["rename", "remove", "newmenu"]);
          this.disableButton(["newfolder"]);
          break;
        case "menuCaption":
          this.enableButton(["rename", "remove"]);
          this.disableButton(["newmenu", "newfolder"]);
      }
      event.currentTarget.focus();
      event.preventDefault();
      return event.stopPropagation();
    };

    CtxMenuManagerView.prototype.onHoverMoveItem = function(event) {};

    CtxMenuManagerView.prototype.onHoverOffMoveItem = function() {};

    CtxMenuManagerView.prototype.onMouseoverDroppable = function() {
      return this.$(".ctxMenus .ui-placeholder").hide();
    };

    CtxMenuManagerView.prototype.onStartSort = function(event, ui) {
      ui.item.find("span[tabindex='0']:first").focus();
      if (/folder/.test(ui.item[0].className)) {
        ui.item.addClass("sorting").find(".ctxMenus").hide();
        return ui.item.prevInfo = {
          contexts: ui.item.parent()[0].className.match(/folders\s(\w+)/)[1],
          order: ui.item.parent().children().index(ui.item),
          text: ui.item.find(".title").text()
        };
      }
    };

    CtxMenuManagerView.prototype.onStopSort = function(event, ui, view) {
      ui.item.find("span[tabindex='0']:first").focus();
      view.$(".folder").removeClass("sorting");
      return view.$(".ctxMenus").show();
    };

    CtxMenuManagerView.prototype.onClickExpandIcon = function(event) {
      var expanded, target$;
      this.$(event.currentTarget).parents(".folder").focus();
      expanded = (target$ = $(event.currentTarget).parents(".contexts")).hasClass("expanded");
      if (expanded) {
        target$.removeClass("expanded");
      } else {
        target$.addClass("expanded");
      }
      windowOnResize();
      return event.stopPropagation();
    };

    CtxMenuManagerView.prototype.setContextMenu = function() {
      var container, context$, ctxMenus, key, that,
        _this = this;
      this.$(".result").empty();
      this.trigger("getCtxMenues", container = {});
      ctxMenus = container.ctxMenus;
      for (key in tmplCtxMenus) {
        this.elResult$.append(context$ = $(this.tmplContexts({
          "contexts": key,
          "dispname": key.substring(0, 1).toUpperCase() + key.substring(1),
          "icon": tmplCtxMenus[key][1]
        })));
        that = this;
        context$.find(".droppable").droppable({
          accept: ".ctxMenuItem:not(.route)",
          tolerance: "pointer",
          hoverClass: "drop-hover",
          over: function() {
            return $(".ctxMenus .ui-placeholder").hide();
          },
          out: function() {
            return $(".ctxMenus .ui-placeholder").show();
          },
          drop: function(event, ui) {
            var target$;
            target$ = $(".folders." + this.className.match(/droppable\s(\w+)/)[1]);
            return ui.draggable.hide("fast", function() {
              return that.onUpdateMenu(null, {
                item: $(this).appendTo(target$).addClass("route").show().find("span[tabindex='0']").focus()
              }, that);
            });
          }
        });
      }
      ctxMenus.forEach(function(ctxMenu) {
        return _this.setContextMenuItem(ctxMenu);
      });
      this.onUpdateMenu(null, null, this);
      return this.onUpdateFolder(null, null, this);
    };

    CtxMenuManagerView.prototype.setContextMenuItem = function(ctxMenu) {
      var dest$, folder;
      if (ctxMenu.parentId === "route") {
        dest$ = this.$(".contexts .folders." + ctxMenu.contexts);
        ctxMenu.route = " route";
      } else {
        ctxMenu.route = "";
        if (!((dest$ = this.$("#" + ctxMenu.parentId + " .ctxMenus")).length > 0)) {
          folder = this.collection.get(ctxMenu.parentId);
          this.$(".contexts .folders." + folder.get("contexts")).append(this.tmplFolder({
            id: folder.id,
            title: folder.get("title")
          }));
          dest$ = this.$("#" + ctxMenu.parentId + " .ctxMenus");
          this.setFolderDroppable(this.$("#" + ctxMenu.parentId));
        }
      }
      return dest$.append(this.tmplMenuItem(ctxMenu));
    };

    CtxMenuManagerView.prototype.tmplContexts = _.template("<div class=\"contexts\">\n  <div class=\"droppable <%=contexts%>\">\n    <span class=\"contexts\" tabindex=\"0\"><i class=\"<%=icon%> contextIcon\"></i><%=dispname%></span>\n  </div>\n  <div class=\"folders <%=contexts%>\"></div>\n</div>");

    CtxMenuManagerView.prototype.tmplFolder = _.template("<div class=\"folder hasFolder\" id=\"<%=id%>\">\n  <span class=\"title\" tabindex=\"0\"><%=title%></span>\n  <div class=\"updown\"></div>\n  <div class=\"emptyFolder\"></div>\n  <form class=\"editCaption\"><input type=\"text\"></form>\n  <div class=\"ctxMenus\"></div>\n</div>");

    CtxMenuManagerView.prototype.tmplMenuItem = _.template("<div class=\"ctxMenuItem<%=route%>\" id=\"<%=id%>\">\n  <span class=\"menuCaption\" tabindex=\"0\" title=\"<%=shortcut%>\"><%=caption%></span>\n  <div class=\"updown\"></div>\n  <form class=\"editCaption\"><input type=\"text\"></form>\n</div>");

    return CtxMenuManagerView;

  })(ExplorerBaseView);

  gMaxItems = 100;

  defaultSleep = 100;

  lastFocused = null;

  keyCodes = {};

  scHelp = null;

  scHelpSect = null;

  keys = null;

  loading = true;

  WebFontConfig = {
    google: {
      families: ['Noto+Sans::latin']
    }
  };

  modeDisp = {
    remap: ["Remap", "icon-random"],
    command: ["Command...", "icon-cog"],
    bookmark: ["Bookmark...", "icon-bookmark"],
    disabled: ["Disabled", "icon-ban-circle"],
    sleep: ["Sleep", "icon-eye-close"],
    comment: ["Comment", "icon-comment-alt"],
    through: ["Pause", "icon-pause", "nodisp"]
  };

  bmOpenMode = {
    current: "Open in current tab",
    newtab: "Open in new tab",
    newwin: "Open in new window",
    incognito: "Open in incognito window"
  };

  escape = function(html) {
    var entity;
    entity = {
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;"
    };
    return html.replace(/[&<>]/g, function(match) {
      return entity[match];
    });
  };

  modifierKeys = ["Ctrl", "Alt", "Shift", "Win", "MouseL", "MouseR", "MouseM"];

  modifierInits = ["c", "a", "s", "w"];

  decodeKbdEvent = function(kbdCode) {
    var keyCombo, keyIdentifier, modifiers, scanCode;
    if (!kbdCode) {
      return null;
    }
    modifiers = parseInt(kbdCode.substring(0, 2), 16);
    scanCode = kbdCode.substring(2);
    if (keyIdentifier = keys[scanCode]) {
      keyCombo = [];
      /*
      for i in [0...modifierKeys.length]
        keyCombo.push modifierKeys[i] if modifiers & Math.pow(2, i)
      */

      if (modifiers & 1) {
        keyCombo.push(modifierKeys[0]);
      }
      if (modifiers & 4) {
        keyCombo.push(modifierKeys[2]);
      }
      if (modifiers & 2) {
        keyCombo.push(modifierKeys[1]);
      }
      if (modifiers & 8) {
        keyCombo.push(modifierKeys[3]);
      }
      if (modifiers & 16) {
        keyCombo.push(modifierKeys[4]);
      }
      if (modifiers & 32) {
        keyCombo.push(modifierKeys[5]);
      }
      if (modifiers & 64) {
        keyCombo.push(modifierKeys[6]);
      }
      if (modifiers & 4) {
        keyCombo.push(keyIdentifier[1] || keyIdentifier[0]);
      } else {
        keyCombo.push(keyIdentifier[0]);
      }
      return keyCombo.join(" + ");
    }
  };

  transKbdEvent = function(value) {
    var i, keyCombo, keyIdenfiers, modifiers, scanCode, _i, _ref4;
    modifiers = parseInt(value.substring(0, 2), 16);
    keyCombo = [];
    for (i = _i = 0, _ref4 = modifierInits.length; 0 <= _ref4 ? _i < _ref4 : _i > _ref4; i = 0 <= _ref4 ? ++_i : --_i) {
      if (modifiers & Math.pow(2, i)) {
        keyCombo.push(modifierInits[i]);
      }
    }
    scanCode = value.substring(2);
    keyIdenfiers = keys[scanCode];
    return "[" + keyCombo.join("") + "]" + keyIdenfiers[0];
  };

  HeaderView = Backbone.View.extend({
    scHelpUrl: "https://support.google.com/chrome/answer/157179?hl=",
    el: "div.header",
    events: {
      "click button.addKeyConfig": "onClickAddKeyConfig",
      "click .ctxmgr": "onClickCtxmgr",
      "change select.kbdtype": "onChangeSelKbd"
    },
    initialize: function(options) {
      var kbdtype, selectKbd$,
        _this = this;
      keys = keyCodes[kbdtype = this.model.get("kbdtype")].keys;
      selectKbd$ = this.$("select.kbdtype");
      $.each(keyCodes, function(key, item) {
        return selectKbd$.append("<option value=\"" + key + "\">" + item.name + "</option>");
      });
      selectKbd$.val(kbdtype);
      return this.setScHelp(kbdtype);
    },
    onClickAddKeyConfig: function(event) {
      return this.trigger("clickAddKeyConfig", event);
    },
    onClickCtxmgr: function() {
      return this.trigger("showPopup", "ctxMenuManager");
    },
    onChangeSelKbd: function(event) {
      this.trigger("changeSelKbd", event);
      return this.setScHelp(this.$("select.kbdtype").val());
    },
    setScHelp0: function(kbdtype) {
      return this.$(".scHelp").text("ショートカットキー一覧").attr("href", this.scHelpUrl + "ja");
    },
    setScHelp: function(kbdtype) {
      if (kbdtype === "JP") {
        return this.$(".scHelp").text("Keyboard shortcuts").attr("href", this.scHelpUrl + "ja");
      } else {
        return this.$(".scHelp").text("Keyboard shortcuts").attr("href", this.scHelpUrl + "en");
      }
    },
    onEnterCtxMenuSelMode: function() {
      return this.$("button").attr("disabled", "disabled").addClass("disabled");
    },
    onLeaveCtxMenuSelMode: function() {
      return this.$("button").removeAttr("disabled").removeClass("disabled");
    }
  });

  Config = Backbone.Model.extend({});

  KeyConfig = Backbone.Model.extend({
    idAttribute: "new",
    defaults: {
      mode: "remap"
    }
  });

  KeyConfigSet = Backbone.Collection.extend({
    model: KeyConfig
  });

  KeyConfigView = Backbone.View.extend({
    kbdtype: null,
    optionKeys: [],
    events: {
      "click .origin,.new": "onClickInput",
      "click div.mode": "onClickMode",
      "click .selectMode div": "onChangeMode",
      "click .edit": "onClickEdit",
      "click .addCommand": "onClickAddCommand",
      "click .copySC": "onClickCopySC",
      "click div.ctxmenu": "onClickCtxMenu",
      "click .pause": "onClickPause",
      "click .resume": "onClickResume",
      "click .delete": "onClickDelete",
      "click .editSleep": "onClickEditSleep",
      "click input.memo,.inputSleep": "onClickInputMemo",
      "click button.cog": "onClickCog",
      "click .updown a": "onClickUpDownChild",
      "focus .new,.origin": "onFocusKeyInput",
      "focus .inputSleep": "onClickInputMemo",
      "keydown .origin": "onKeydownOrigin",
      "keydown .new": "onKeydownNew",
      "submit  .memo": "onSubmitMemo",
      "submit  .formSleep": "onSubmitSleep",
      "blur  .selectMode": "onBlurSelectMode",
      "blur  .selectCog": "onBlurSelectCog",
      "blur  input.memo": "onBlurInputMemo",
      "blur  .inputSleep": "onBlurInputSleep",
      "mouseover": "onMouseOverChild",
      "mouseout": "onMouseOutChild"
    },
    initialize: function(options) {
      this.optionKeys = _.keys(modeDisp);
      this.model.on({
        "change:bookmark": this.onChangeBookmark,
        "change:command": this.onChangeCommand,
        "change:ctxMenu": this.onChangeCtxmenu,
        "setFocus": this.onClickInput,
        "remove": this.onRemove,
        "setUnselectable": this.onSetUnselectable,
        "setRowspan": this.onSetRowspan,
        "updatePosition": this.onUpdatePosition,
        "showPopup": this.onShowPopup,
        "triggerEventCtxMenuSelected": this.onTriggerCtxMenuSelected
      }, this);
      return this.model.collection.on({
        "kbdEvent": this.onKbdEvent,
        "changeKbd": this.onChangeKbd,
        "updateOrderByEl": this.onUpdateOrderByEl,
        "mouseoverchild": this.onMouseOverChild,
        "mouseoutchild": this.onMouseOutChild
      }, this);
    },
    render: function(kbdtype) {
      var mode;
      this.setElement(this.template({
        options: modeDisp
      }));
      mode = this.model.get("mode");
      if (/^C/.test(this.model.id)) {
        this.$el.addClass("child").find("th:first-child").remove().end().find(".disabled").hide();
      } else if (!this.setKbdValue(this.$(".new"), this.model.id)) {
        this.state = "invalid";
      } else {
        this.$el.find(".sleep").hide();
        this.onSetRowspan();
      }
      if (!(this.$el.hasClass("parent") || this.$el.hasClass("child"))) {
        this.$el.find(".comment").hide();
      }
      this.setKbdValue(this.$(".origin"), this.model.get("origin"));
      this.kbdtype = kbdtype;
      this.onChangeMode(null, mode);
      return this;
    },
    onChangeBookmark: function() {
      return this.onChangeMode(null, "bookmark");
    },
    onChangeCommand: function() {
      return this.onChangeMode(null, "command");
    },
    onChangeCtxmenu: function() {
      var container, ctxMenu;
      if ((ctxMenu = this.model.get("ctxMenu")) && !this.$el.hasClass("child")) {
        if (ctxMenu.parentId !== "route") {
          this.model.collection.trigger("getCtxMenuContexts", container = {
            parentId: ctxMenu.parentId
          });
          ctxMenu.contexts = container.contexts;
        }
        this.$("td.ctxmenu").html("<div class=\"ctxmenu-icon\" title=\"Context menu for " + ctxMenu.contexts + "\n Title: " + ctxMenu.caption + "\"><i class=\"" + tmplCtxMenus[ctxMenu.contexts][1] + "\"></i></div>");
        this.$("div.ctxmenu")[0].childNodes[1].nodeValue = " Edit context menu...";
      } else if (this.model.get("mode") !== "disabled" && !this.$el.hasClass("child")) {
        this.$("td.ctxmenu").empty();
        this.$("div.ctxmenu")[0].childNodes[1].nodeValue = " Create context menu...";
      }
      return this.trigger("resizeInput");
    },
    onRemove: function() {
      var parentId;
      if (parentId = this.model.get("parentId")) {
        this.model.collection.trigger("mouseoutchild", parentId);
      }
      this.model.collection.off(null, null, this);
      this.model.off(null, null, this);
      this.off(null, null, null);
      return this.remove();
    },
    onSetUnselectable: function(unSelectable) {
      if (unSelectable) {
        return this.$el.addClass("unselectable");
      } else {
        return this.$el.removeClass("unselectable");
      }
    },
    onTriggerCtxMenuSelected: function() {
      var shortcut;
      if (this.$el.hasClass("unselectable")) {
        return this.$el.removeClass("ui-selected unselectable");
      } else if (this.$el.hasClass("ui-selected")) {
        this.$el.removeClass("ui-selected");
        shortcut = decodeKbdEvent(this.model.id);
        return this.trigger("addCtxMenu", {
          id: this.model.id,
          caption: this.getDescription() || shortcut,
          shortcut: shortcut
        });
      }
    },
    onSetRowspan: function() {
      var models;
      if ((models = this.model.collection.where({
        parentId: this.model.id
      })).length > 0) {
        this.$el.addClass("parent").find(".selectMode .comment").show();
        this.$("th:first-child").attr("rowspan", models.length + 1);
        return this.model.set("batch", true);
      } else {
        this.$el.removeClass("parent");
        this.$("th:first-child").removeAttr("rowspan");
        this.model.unset("batch");
        if (!this.$el.hasClass("child")) {
          this.$(".selectMode .comment").hide();
          return this.$("ul.updown").remove();
        }
      }
    },
    onShowPopup: function(selected) {
      if (selected) {
        return this.$el.addClass("ui-selected");
      } else {
        return this.$el.removeClass("ui-selected");
      }
    },
    onKbdEvent: function(value) {
      var input$, scanCode;
      input$ = this.$("div:focus");
      if (input$.length > 0) {
        if (input$.hasClass("new")) {
          if (this.model.id !== value && this.model.collection.findWhere({
            "new": value
          })) {
            $("#tiptip_content").text("\"" + (decodeKbdEvent(value)) + "\" already exists.");
            input$.tipTip();
            return;
          }
          this.model.collection.where({
            parentId: this.model.id
          }).forEach(function(child) {
            return child.set("parentId", value);
          });
        } else {
          scanCode = ~~value.substring(2);
          if (scanCode >= 0x200 || scanCode === 0x15D) {
            return;
          }
        }
        this.setKbdValue(input$, value);
        this.model.set(input$[0].className.match(/(new|origin)/)[0], value);
        this.setDesc();
        this.trigger("resizeInput");
        if (input$.hasClass("new") && this.model.has("ctxMenu")) {
          return this.trigger("remakeCtxMenu", {
            dfd: $.Deferred()
          });
        }
      }
    },
    onChangeKbd: function(kbdtype) {
      this.kbdtype = kbdtype;
      this.setKbdValue(this.$(".new"), this.model.id);
      this.setKbdValue(this.$(".origin"), this.model.get("origin"));
      return this.setDesc();
    },
    onUpdateOrderByEl: function() {
      return this.model.set("order", this.$el.parent().children().index(this.$el));
    },
    onUpdatePosition: function() {
      return this.$el.parent()[0].insertBefore(this.el, this.$el.parent().children().eq(this.model.get("order")).get(0) || null);
    },
    onKeydownOrigin: function(event) {
      var i, keyname, keynames, scCode, scanCode, _i, _ref4;
      if (keynames = keyIdentifiers[this.kbdtype][event.originalEvent.keyIdentifier]) {
        if (event.originalEvent.shiftKey) {
          if (!(keyname = keynames[1])) {
            return;
          }
          scCode = "04";
        } else {
          keyname = keynames[0];
          scCode = "00";
        }
        for (i = _i = 0, _ref4 = keys.length; 0 <= _ref4 ? _i < _ref4 : _i > _ref4; i = 0 <= _ref4 ? ++_i : --_i) {
          if (keys[i] && (keyname === keys[i][0] || keyname === keys[i][1])) {
            scanCode = i;
            break;
          }
        }
        if (scanCode) {
          scCode += i;
          if (event.originalEvent.shiftKey) {
            this.$(".origin").html("<span>Shift</span>+<span>" + keyname + "</span>");
          } else {
            this.$(".origin").html("<span>" + keyname + "</span>");
          }
          this.model.set("origin", scCode);
          this.setDesc();
          return this.trigger("resizeInput");
        }
      }
    },
    onClickCopySC: function(event) {
      var body, children, command, desc, keyCombo, method, mode, scCode, text;
      if ((mode = this.model.get("mode")) === "through") {
        mode = this.model.get("lastMode");
      }
      if ((children = this.model.collection.where({
        parentId: this.model.id
      })).length > 0) {
        mode = "batch";
      }
      if (mode === "remap") {
        method = "keydown";
        scCode = this.model.get("origin");
        desc = this.$(".desc").find(".content,.memo").text();
      } else {
        method = "send";
        scCode = this.model.id;
        desc = this.$(".desc").find(".content,.command,.commandCaption,.bookmark,.memo").text();
      }
      command = this.$("td.options .mode").text().replace("Remap", "");
      if (command) {
        command = " " + command + ":";
      }
      keyCombo = (decodeKbdEvent(scCode)).replace(/\s/g, "");
      if (desc) {
        desc = " " + desc;
      }
      body = "scd." + method + "('" + (transKbdEvent(scCode)) + "');";
      text = body + " /* " + keyCombo + command + desc + " */";
      return chrome.runtime.sendMessage({
        action: "setClipboard",
        value1: text
      }, function(msg) {});
    },
    getDescription: function() {
      var desc;
      if (this.model.get("mode") === "remap") {
        desc = this.$(".desc").find(".content,.memo").text();
      } else {
        desc = this.$(".desc").find(".content,.command,.commandCaption,.bookmark,.memo").text();
      }
      return $.trim(desc);
    },
    onClickCtxMenu: function() {
      return this.trigger("showPopup", "ctxMenuOptions", this.model, {
        desc: this.getDescription()
      });
    },
    onClickInputMemo: function(event) {
      return event.stopPropagation();
    },
    onSubmitMemo: function() {
      this.$("form.memo").hide();
      this.model.set({
        "memo": this.$("div.memo").show().html(escape(this.$("input.memo").val())).text()
      });
      endEdit();
      return false;
    },
    onClickMode: function(event) {
      if (event.currentTarget.getAttribute("title") === "Pause") {
        return;
      }
      if (this.$(".selectMode").toggle().is(":visible")) {
        this.$(".selectMode").focus();
        this.$(".mode").addClass("selecting");
      } else {
        this.$(".mode").removeClass("selecting");
      }
      return event.stopPropagation();
    },
    onChangeMode: function(event, mode) {
      if (event) {
        this.$(".mode").removeClass("selecting");
        mode = event.currentTarget.className;
        this.$(".selectMode").hide();
        if (mode === "bookmark" || mode === "command") {
          this.trigger("showPopup", mode, this.model, this.model.get(mode));
          return;
        }
      }
      this.model.set("mode", mode);
      this.setDispMode(mode);
      this.setDesc();
      return this.trigger("resizeInput");
    },
    onBlurSelectMode: function() {
      this.$(".selectMode").hide();
      return this.$(".mode").removeClass("selecting");
    },
    onFocusKeyInput: function() {
      return lastFocused = this.el;
    },
    onClickInput: function(event, selector) {
      if (event) {
        $(event.currentTarget).focus();
      } else if (selector) {
        this.$(selector).focus();
      } else {
        this.$(".origin").focus();
      }
      return event != null ? event.stopPropagation() : void 0;
    },
    onBlurInputMemo: function() {
      return this.onSubmitMemo();
    },
    onClickCog: function(event) {
      if (this.$(".selectCog").toggle().is(":visible")) {
        this.$(".selectCog").focus();
        $(event.currentTarget).addClass("selecting");
      } else {
        $(event.currentTarget).removeClass("selecting");
      }
      return event.stopPropagation();
    },
    onBlurSelectCog: function() {
      this.$(".selectCog").hide();
      return this.$("button.cog").removeClass("selecting");
    },
    onClickEdit: function(event) {
      var editing, input$, memo, mode;
      if ((mode = this.model.get("mode")) === "through") {
        mode = this.model.get("lastMode");
      }
      switch (mode) {
        case "bookmark":
          return this.trigger("showPopup", "bookmarkOptions", this.model, this.model.get("bookmark"));
        case "command":
          return this.trigger("showPopup", "commandOptions", this.model, this.model.get("command"));
        default:
          (memo = this.$("div.memo")).toggle();
          editing = (input$ = this.$("form.memo").toggle().find("input.memo")).is(":visible");
          if (editing) {
            input$.focus().val(memo.text());
            startEdit();
          } else {
            this.onSubmitMemo();
          }
          return event.stopPropagation();
      }
    },
    onClickAddCommand: function() {
      var parentId;
      if (/^C/.test(parentId = this.model.get("new"))) {
        parentId = this.model.get("parentId");
      }
      lastFocused = this.el;
      this.model.collection.add({
        "new": getUuid("C"),
        "origin": ~~parentId.substring(2) >= 0x200 ? "0130" : parentId,
        "parentId": parentId
      });
      if (this.$el.hasClass("parent")) {
        this.setDispMode(this.model.get("mode"));
        if (!(this.$("ul.updown").length > 0)) {
          return this.$(".desc").append(this.tmplUpDown);
        }
      }
    },
    onMouseOverChild: function(event, id) {
      var parentId;
      if (id === this.model.id) {
        this.$el.addClass("hover");
      }
      if (event && (parentId = this.model.get("parentId"))) {
        return this.model.collection.trigger("mouseoverchild", null, parentId);
      }
    },
    onMouseOutChild: function(event, id) {
      var parentId;
      if (id === this.model.id) {
        this.$el.removeClass("hover");
      }
      if (event && (parentId = this.model.get("parentId"))) {
        return this.model.collection.trigger("mouseoutchild", null, parentId);
      }
    },
    onClickPause: function() {
      var ctxMenu;
      this.model.set("lastMode", this.model.get("mode"));
      this.onChangeMode(null, "through");
      if (ctxMenu = this.model.get("ctxMenu")) {
        return andy.updateCtxMenu(this.model.id, ctxMenu, true);
      }
    },
    onClickResume: function() {
      var ctxMenu;
      this.onChangeMode(null, this.model.get("lastMode"));
      if (ctxMenu = this.model.get("ctxMenu")) {
        return andy.updateCtxMenu(this.model.id, ctxMenu, false);
      }
    },
    onClickDelete: function() {
      var children, collection, desc, msg, parentId, shortcut,
        _this = this;
      if (parentId = this.model.get("parentId")) {
        shortcut = "";
        desc = "'" + this.getDescription() + "'";
        switch (this.model.get("mode")) {
          case "remap":
            shortcut = decodeKbdEvent(this.model.get("origin")) + "\n\n ";
            break;
          case "sleep":
            shortcut = "Sleep " + this.model.get("sleep") + " msec";
            desc = "";
        }
        children = [];
        msg = "Are you sure you want to delete this child command?\n\n " + shortcut + desc;
      } else {
        if ((children = this.model.collection.where({
          parentId: this.model.id
        })).length > 0) {
          msg = "Are you sure you want to delete this shortcut and all the child commands?";
        } else {
          msg = "Are you sure you want to delete this shortcut?";
        }
        shortcut = decodeKbdEvent(this.model.id);
        msg = msg + ("\n\n " + shortcut + "\n\n '" + (this.getDescription()) + "'");
      }
      if (confirm(msg)) {
        children.forEach(function(child) {
          return _this.trigger("removeConfig", child);
        });
        collection = this.model.collection;
        this.trigger("removeConfig", this.model);
        if (parentId) {
          return collection.get(parentId).trigger("setRowspan");
        }
      } else {
        return this.$(".selectCog").blur();
      }
    },
    onClickUpDownChild: function(event) {
      var changeProperty, childModel, models, newChild$, newParent$, order, parentId, parentModel,
        _this = this;
      changeProperty = function() {
        var childId;
        childId = childModel.id;
        childModel.set("new", "temp");
        childModel.unset("parentId");
        parentModel.set("new", childId);
        parentModel.set("parentId", parentId);
        childModel.set("new", parentId);
        newParent$.removeClass("child").find(".disabled").show().end().prepend(newChild$.find("th:first-child")).find("td.ctxmenu").append(newChild$.find("div.ctxmenu-icon")).end().find(".desc").find(".ctxmenu,.copySC").show();
        return newChild$.removeClass("parent hover").addClass("child").find(".disabled").hide().end().find(".desc").find(".ctxmenu,.copySC").hide();
      };
      order = -1;
      parentId = this.model.get("parentId") || this.model.id;
      models = [parentModel = this.model.collection.get(parentId)].concat(this.model.collection.where({
        parentId: parentId
      }));
      $.each(models, function(i, model) {
        if (model.id === _this.model.id) {
          order = i;
          return false;
        }
      });
      if (event.currentTarget.title === "up" && order > 0) {
        (newChild$ = this.$el.prev()).before(newParent$ = this.$el);
        if (order === 1) {
          childModel = this.model;
          changeProperty();
        }
        return this.trigger("updateChildPos");
      } else if (event.currentTarget.title === "down" && models.length > (order + 1)) {
        (newChild$ = this.$el).before((newParent$ = this.$el.next()));
        if (order === 0) {
          childModel = models[1];
          changeProperty();
        }
        return this.trigger("updateChildPos");
      }
    },
    onClickEditSleep: function() {
      var _this = this;
      this.$(".dispSleep").hide();
      this.$(".inputSleep").show().val(this.model.get("sleep"));
      return setTimeout((function() {
        return _this.$(".inputSleep").focus();
      }), 0);
    },
    onSubmitSleep: function() {
      var value;
      value = this.$(".inputSleep").val();
      if (!value) {
        value = 100;
      } else {
        if (value < 0) {
          value = 0;
        }
        if (value > 60000) {
          value = 60000;
        }
      }
      value = Math.round(value);
      this.model.set({
        "sleep": value
      });
      this.$(".dispSleep").show().html(value).attr("title", "Sleep " + value + " msec");
      this.$(".inputSleep").hide();
      return false;
    },
    onBlurInputSleep: function() {
      return this.onSubmitSleep();
    },
    setDispMode: function(mode) {
      this.$(".mode").attr("title", modeDisp[mode][0].replace("...", "")).find(".icon")[0].className = "icon " + modeDisp[mode][1];
      if (mode === "through") {
        mode = this.model.get("lastMode") + " through";
      }
      this.$(".new,.origin,.icon-arrow-right").removeClass(this.optionKeys.join(" ")).addClass(mode);
      if (/remap/.test(mode)) {
        this.$("th:first,th:eq(1)").removeAttr("colspan").css("padding", "").find("i").show();
        return this.$("th:eq(1),th:eq(2),th .origin").show().find("i").show();
      } else {
        if (this.$el.hasClass("child")) {
          this.$("th:first").css("padding", "16px 0").find("i").hide();
          return this.$("th .origin").hide();
        } else if (this.$el.hasClass("parent")) {
          this.$("th:first").removeAttr("colspan");
          this.$("th:eq(1),th:eq(2)").show();
          this.$("th:eq(1)").css("padding", "18px 0").find("i").hide();
          return this.$("th .origin").hide();
        } else {
          this.$("th:first").attr("colspan", "3");
          return this.$("th:eq(1),th:eq(2)").hide();
        }
      }
    },
    setKbdValue: function(input$, value) {
      var result;
      if (result = decodeKbdEvent(value)) {
        input$.html(_.map(result.split(" + "), function(s) {
          return "<span>" + s + "</span>";
        }).join("+"));
        return true;
      } else {
        return false;
      }
    },
    setDesc: function() {
      var bookmark, command, commandDisp, content, content3row, desc, editOption, help, i, key, keycombo, lang, lines, mode, pause, sleep, tdDesc, test, _i, _j, _ref4, _ref5;
      (tdDesc = this.$(".desc")).empty();
      editOption = {
        iconName: "",
        command: ""
      };
      if ((mode = this.model.get("mode")) === "through") {
        pause = true;
        mode = this.model.get("lastMode");
      }
      switch (mode) {
        case "sleep":
          if (!(sleep = this.model.get("sleep"))) {
            this.model.set("sleep", sleep = 100);
          }
          tdDesc.append(this.tmplSleep({
            sleep: sleep
          }));
          break;
        case "bookmark":
          bookmark = this.model.get("bookmark");
          tdDesc.append(this.tmplBookmark({
            openmode: bmOpenMode[bookmark.openmode],
            url: bookmark.url,
            title: bookmark.title
          }));
          editOption = {
            iconName: "icon-wrench",
            command: "Edit bookmark..."
          };
          break;
        case "command":
          desc = (commandDisp = commandsDisp[this.model.get("command").name])[1];
          if (commandDisp[2]) {
            content3row = [];
            command = this.model.get("command");
            lines = command.content.split("\n");
            for (i = _i = 0, _ref4 = lines.length; 0 <= _ref4 ? _i < _ref4 : _i > _ref4; i = 0 <= _ref4 ? ++_i : --_i) {
              if (i > 2) {
                content3row[i - 1] += " ...";
                break;
              } else {
                content3row.push(lines[i].replace(/"/g, "'"));
              }
            }
            tdDesc.append(this.tmplCommandCustom({
              ctg: commandDisp[3],
              desc: desc,
              content3row: content3row.join("\n"),
              caption: command.caption
            }));
            editOption = {
              iconName: "icon-wrench",
              command: "Edit command..."
            };
          } else {
            tdDesc.append(this.tmplCommand({
              desc: desc,
              ctg: commandDisp[0].substring(0, 1).toUpperCase() + commandDisp[0].substring(1)
            }));
          }
          break;
        case "remap":
        case "disabled":
          lang = this.kbdtype === "JP" ? "ja" : "en";
          if (mode === "remap") {
            keycombo = this.$(".origin").text();
          } else {
            keycombo = this.$(".new").text();
          }
          keycombo = (keycombo.replace(/\s/g, "")).toUpperCase();
          if (!(help = scHelp[keycombo])) {
            if (/^CTRL\+[2-7]$/.test(keycombo)) {
              help = scHelp["CTRL+1"];
            }
          }
          if (help　 && help[lang]) {
            for (i = _j = 0, _ref5 = help[lang].length; 0 <= _ref5 ? _j < _ref5 : _j > _ref5; i = 0 <= _ref5 ? ++_j : --_j) {
              test = help[lang][i].match(/(^\w+)\^(.+)/);
              key = RegExp.$1;
              content = RegExp.$2;
              tdDesc.append(this.tmplHelp({
                sectDesc: scHelpSect[key],
                sectKey: key,
                scHelp: content
              })).find(".sectInit").tooltip({
                position: {
                  my: "left+10 top-60"
                },
                tooltipClass: "tooltipClass"
              });
            }
          }
      }
      if (tdDesc.html() === "") {
        tdDesc.append(this.tmplMemo({
          memo: this.model.get("memo")
        }));
        editOption = {
          iconName: "icon-pencil",
          command: "Edit comment"
        };
      }
      tdDesc.append(this.tmplDesc(editOption));
      if (mode === "disabled") {
        this.$(".addKey,.copySC,.seprater.1st,div.ctxmenu").hide();
      }
      if (editOption.iconName === "") {
        tdDesc.find(".edit").hide();
      }
      if (pause) {
        tdDesc.find(".pause").hide();
      } else {
        tdDesc.find(".resume").hide();
      }
      if (this.$el.hasClass("child")) {
        tdDesc.find(".ctxmenu,.copySC").hide();
      }
      if (this.$el.hasClass("child") || this.$el.hasClass("parent")) {
        tdDesc.append(this.tmplUpDown);
      }
      return this.onChangeCtxmenu();
    },
    tmplDesc: _.template("<button class=\"cog small\" title=\"menu\"><i class=\"icon-caret-down\"></i></button>\n<div class=\"selectCog\" tabIndex=\"0\">\n  <div class=\"edit\"><i class=\"<%=iconName%>\"></i> <%=command%></div>\n  <div class=\"addCommand\"><i class=\"icon-plus\"></i> Add command</div>\n  <div class=\"ctxmenu\"><i class=\"icon-reorder\"></i> Create context menu...</div>\n  <div class=\"copySC\"><i class=\"icon-paper-clip\"></i> Copy script</div>\n  <span class=\"seprater 1st\"><hr style=\"margin:3px 1px\" noshade></span>\n  <div class=\"pause\"><i class=\"icon-pause\"></i> Pause</div>\n  <div class=\"resume\"><i class=\"icon-play\"></i> Resume</div>\n  <span class=\"seprater\"><hr style=\"margin:3px 1px\" noshade></span>\n  <div class=\"delete\"><i class=\"icon-trash\"></i> Delete</div>\n</div>"),
    tmplUpDown: "    <ul class=\"button-bar updown\">\n      <li class=\"first\"><a href=\"#\" title=\"up\"><i class=\"icon-chevron-up\"></i></a></li>\n  <li class=\"last\"><a href=\"#\" title=\"down\"><i class=\"icon-chevron-down\"></i></a></li>\n</ul>",
    tmplMemo: _.template("<form class=\"memo\">\n  <input type=\"text\" class=\"memo\">\n</form>\n<div class=\"memo\"><%=memo%></div>"),
    tmplSleep: _.template("<form class=\"formSleep\">\n  <input type=\"number\" class=\"inputSleep\" min=\"0\" max=\"60000\" step=\"10\" required>\n  <span class=\"dispSleep\" title=\"Sleep <%=sleep%> msec\"><%=sleep%></span>\n  <i class=\"icon-pencil editSleep\" title=\"Edit sleep msec(0-60000)\"></i>\n</form>"),
    tmplBookmark: _.template("<div class=\"bookmark\" title=\"<<%=openmode%>>\n<%=url%>\" style=\"background-image:-webkit-image-set(url(chrome://favicon/size/16@1x/<%=url%>) 1x);\"><%=title%></div>"),
    tmplCommand: _.template("<div class=\"ctgIcon <%=ctg%>\"><%=ctg%></div><div class=\"command\"><%=desc%></div>"),
    tmplCommandCustom: _.template("<div class=\"ctgIcon <%=ctg%>\" title=\"<%=desc%>\"><%=ctg%></div><div class=\"commandCaption\" title=\"<%=content3row%>\"><%=caption%></div>"),
    tmplHelp: _.template("<div class=\"sectInit\" title=\"<%=sectDesc%>\"><%=sectKey%></div><div class=\"content\"><%=scHelp%></div>"),
    template: _.template("<tr class=\"data\">\n  <th>\n    <div class=\"new\" tabIndex=\"0\"></div>\n    <div class=\"grpbartop\"></div>\n    <div class=\"grpbarbtm\"></div>\n  </th>\n  <th>\n    <i class=\"icon-arrow-right\"></i>\n  </th>\n  <th class=\"tdOrigin\">\n    <div class=\"origin\" tabIndex=\"-1\"></div>\n  </th>\n  <td class=\"options\">\n    <div class=\"mode\"><i class=\"icon\"></i><span></span><i class=\"icon-caret-down\"></i></div>\n    <div class=\"selectMode\" tabIndex=\"0\">\n      <% _.each(options, function(option, key) { if (option[2] != \"nodisp\") { %>\n      <div class=\"<%=key%>\"><i class=\"icon <%=option[1]%>\"></i> <%=option[0]%></div>\n      <% }}); %>\n    </div>\n  <td class=\"ctxmenu\"></td>\n  <td class=\"desc\"></td>\n  <td class=\"blank\">&nbsp;</td>\n</tr>")
  });

  KeyConfigSetView = Backbone.View.extend({
    placeholder: "Enter new shortcut key",
    el: "table.keyConfigSetView",
    events: {
      "click .addnew": "onClickAddnew",
      "blur  .addnew": "onBlurAddnew",
      "click": "onClickBlank"
    },
    initialize: function(options) {
      this.collection.comparator = function(model) {
        return model.get("order");
      };
      return this.collection.on({
        add: this.onAddRender,
        kbdEvent: this.onKbdEvent
      }, this);
    },
    render: function(keyConfigSet) {
      var _this = this;
      this.$el.append(this.template());
      this.collection.set(keyConfigSet);
      this.$("tbody").sortable({
        delay: 300,
        scroll: true,
        cancel: "tr.border,tr.child,input",
        cursor: "move",
        start: function() {
          return _this.onStartSort();
        },
        stop: function() {
          return _this.redrawTable();
        }
      });
      $(".fixed-table-container-inner").niceScroll({
        cursorwidth: 13,
        cursorborderradius: 2,
        smoothscroll: true,
        cursoropacitymin: .3,
        cursoropacitymax: .7,
        zindex: 999998
      });
      this.niceScroll = $(".fixed-table-container-inner").getNiceScroll();
      loading = false;
      this.redrawTable();
      return this;
    },
    onAddRender: function(model) {
      var divAddNew, keyConfigView, tbody;
      keyConfigView = new KeyConfigView({
        model: model
      });
      keyConfigView.on("removeConfig", this.onChildRemoveConfig, this);
      keyConfigView.on("resizeInput", this.onChildResizeInput, this);
      keyConfigView.on("showPopup", this.onShowPopup, this);
      keyConfigView.on("addCtxMenu", this.onAddCtxMenu, this);
      keyConfigView.on("updateChildPos", this.redrawTable, this);
      keyConfigView.on("remakeCtxMenu", this.onRemakeCtxMenu, this);
      divAddNew = this.$("tr.addnew")[0] || null;
      tbody = this.$("tbody")[0];
      if (/^C/.test(model.id) && lastFocused) {
        divAddNew = lastFocused.nextSibling || null;
      }
      tbody.insertBefore(keyConfigView.render(this.model.get("kbdtype")).el, divAddNew);
      tbody.insertBefore($(this.tmplBorder)[0], divAddNew);
      if (keyConfigView.state === "invalid") {
        this.onChildRemoveConfig(model);
      }
      if (divAddNew || /^C/.test(model.id) && !loading) {
        this.$("div.addnew").blur();
        this.redrawTable();
      }
      if (/^C/.test(model.id) && lastFocused) {
        lastFocused = null;
        this.collection.get(model.get("parentId")).trigger("setRowspan");
        return setTimeout((function() {
          return model.trigger("setFocus");
        }), 0);
      }
    },
    onKbdEvent: function(value) {
      var model, newitem, target;
      if (this.$(".addnew").length === 0) {
        if ((target = this.$(".new:focus,.origin:focus")).length === 0) {
          if (model = this.collection.get(value)) {
            model.trigger("setFocus", null, ".new");
            return;
          } else {
            if (!this.onClickAddKeyConfig()) {
              return;
            }
          }
        } else {
          return;
        }
      }
      if (this.collection.findWhere({
        "new": value
      })) {
        $("#tiptip_content").text("\"" + (decodeKbdEvent(value)) + "\" already exists.");
        this.$("div.addnew").tipTip();
        return;
      }
      this.collection.add(newitem = new KeyConfig({
        "new": value,
        origin: ~~value.substring(2) >= 0x200 ? "0130" : value
      }));
      this.$("tbody").sortable("enable").sortable("refresh");
      windowOnResize();
      this.onChildResizeInput();
      return newitem.trigger("setFocus");
    },
    onChildRemoveConfig: function(model) {
      this.collection.remove(model);
      this.redrawTable();
      windowOnResize();
      return this.onChildResizeInput();
    },
    onChildResizeInput: function() {
      var _this = this;
      this.$(".th_inner").css("left", 0);
      return setTimeout((function() {
        return _this.$(".th_inner").css("left", "");
      }), 0);
    },
    onShowPopup: function(name, model, options) {
      return this.trigger("showPopup", name, model, options);
    },
    onRemakeCtxMenu: function(container) {
      return andy.remakeCtxMenu(this.getSaveData()).done(function() {
        return container.dfd.resolve();
      });
    },
    onAddCtxMenu: function(ctxMenu) {
      return this.trigger("addCtxMenu", ctxMenu);
    },
    onTriggerEventSelected: function() {
      this.collection.models.forEach(function(model) {
        return model.trigger("triggerEventCtxMenuSelected");
      });
      return this.redrawTable();
    },
    onSetCtxMenus: function(ctxMenus) {
      var _this = this;
      this.collection.models.forEach(function(model) {
        return model.unset("ctxMenu");
      });
      return ctxMenus.forEach(function(ctxMenu) {
        var model;
        model = _this.collection.get(ctxMenu.id);
        return model.set("ctxMenu", ctxMenu);
      });
    },
    onGetCtxMenues: function(container) {
      container.ctxMenus = [];
      this.collection.models.forEach(function(model) {
        var ctxMenu;
        if (ctxMenu = model.get("ctxMenu")) {
          return container.ctxMenus.push({
            id: model.id,
            caption: ctxMenu.caption,
            contexts: ctxMenu.contexts,
            parentId: ctxMenu.parentId,
            shortcut: decodeKbdEvent(model.id),
            order: ctxMenu.order || 999
          });
        }
      });
      return container.ctxMenus.sort(function(a, b) {
        return a.order - b.order;
      });
    },
    onEnterCtxMenuSelMode: function(entried) {
      this.$("button").attr("disabled", "disabled").addClass("disabled");
      this.collection.models.forEach(function(model) {
        var _ref4;
        return model.trigger("setUnselectable", (_ref4 = model.id, __indexOf.call(entried, _ref4) >= 0) ? true : false);
      });
      this.$("tbody").sortable("disable").selectable({
        cancel: "tr:has(div.ctxmenu-icon)",
        filter: "tr"
      }).find("tr:has(div.mode[title='Disabled'])").addClass("unselectable").end().find("tr:has(div.ctxmenu-icon)").addClass("unselectable").end().find("div.mode,div.new,div.origin").addClass("unselectable").end();
      return this.onStartSort();
    },
    onLeaveCtxMenuSelMode: function(cancel) {
      this.$("button").removeAttr("disabled").removeClass("disabled");
      this.$("tbody").selectable("destroy").sortable("enable").find("div.unselectable").removeClass("unselectable").end();
      if (cancel) {
        this.$("tr").removeClass("ui-selected unselectable");
        return this.redrawTable();
      }
    },
    onGetEditerSize: function(container) {
      var editerSize;
      if (editerSize = this.model.get("editerSize")) {
        container.width = editerSize.width;
        return container.height = editerSize.height;
      }
    },
    onSetEditerSize: function(width, height) {
      return this.model.set("editerSize", {
        width: width,
        height: height
      });
    },
    onClickAddKeyConfig: function(event) {
      var newItem$;
      if (this.$(".addnew").length > 0) {
        return;
      }
      if (this.collection.length > gMaxItems) {
        $("#tiptip_content").text("You have reached the maximum number of items. (Max " + gMaxItems + " items)");
        $(event.currentTarget).tipTip({
          defaultPosition: "left"
        });
        return false;
      }
      newItem$ = $(this.tmplAddNew({
        placeholder: this.placeholder
      }));
      if (/child/.test(lastFocused != null ? lastFocused.className : void 0)) {
        lastFocused = $(lastFocused).prevAll(".parent:first")[0];
      }
      this.$("tbody")[0].insertBefore(newItem$[0], lastFocused);
      newItem$.find(".addnew").focus()[0].scrollIntoViewIfNeeded();
      this.$("tbody").sortable("disable");
      return windowOnResize();
    },
    onClickBlank: function() {
      this.$(":focus").blur();
      return lastFocused = null;
    },
    onClickAddnew: function(event) {
      return event.stopPropagation();
    },
    onBlurAddnew: function() {
      this.$(".addnew").remove();
      this.$("tbody").sortable("enable");
      return windowOnResize();
    },
    onChangeSelKbd: function(event) {
      var newKbd;
      keys = keyCodes[newKbd = event.currentTarget.value].keys;
      this.collection.trigger("changeKbd", newKbd);
      return this.model.set("kbdtype", newKbd);
    },
    onStartSort: function() {
      this.$("tr.child").hide();
      this.$(".ui-sortable-placeholder").nextAll("tr.border:first,tr.border:last").remove();
      return this.$(".parent th:first-child").removeAttr("rowspan");
    },
    redrawTable: function() {
      var _this = this;
      this.$("tr.child").show();
      this.$("tr.border").remove();
      this.collection.models.forEach(function(model) {
        return model.trigger("setRowspan");
      });
      $("#sortarea").append(this.$("tr.data"));
      this.collection.trigger("updateOrderByEl");
      this.collection.sort();
      this.collection.models.forEach(function(model) {
        var parentId;
        if (parentId = model.get("parentId")) {
          return model.set("order", 999);
        }
      });
      this.collection.sort();
      this.collection.models.forEach(function(model) {
        var parentId;
        if (parentId = model.get("parentId")) {
          return model.set("order", _this.collection.get(parentId).get("order"));
        }
      });
      this.collection.sort();
      $.each(this.collection.models, function(i, model) {
        model.set("order", i);
        return model.trigger("updatePosition");
      });
      $.each($("#sortarea tr"), function(i, tr) {
        return _this.$("tbody").append(tr);
      });
      this.$("tr.last").removeClass("last");
      return $.each(this.$("tbody > tr"), function(i, tr) {
        var tr$, _ref4;
        if (!/child/.test((_ref4 = tr.nextSibling) != null ? _ref4.className : void 0)) {
          (tr$ = $(tr)).after(_this.tmplBorder);
          if (/child/.test(tr.className)) {
            return tr$.addClass("last");
          }
        }
      });
    },
    getSaveData: function() {
      this.collection.remove(this.collection.findWhere({
        "new": this.placeholder
      }));
      return {
        config: this.model.toJSON(),
        ctxMenuFolderSet: ctxMenuManagerView.collection.sort().toJSON(),
        keyConfigSet: this.collection.toJSON()
      };
    },
    tmplAddNew: _.template("<tr class=\"addnew\">\n  <th colspan=\"3\">\n    <div class=\"new addnew\" tabIndex=\"0\"><%=placeholder%></div>\n  </th>\n  <td></td><td></td><td></td><td class=\"blank\"></td>\n</tr>"),
    tmplBorder: "<tr class=\"border\">\n  <td colspan=\"6\"><div class=\"border\"></div></td>\n  <td></td>\n</tr>",
    template: _.template("<thead>\n  <tr>\n    <th>\n      <div class=\"th_inner\">New <i class=\"icon-arrow-right\"></i> Origin shortcut key</div>\n    </th>\n    <th></th>\n    <th></th>\n    <th>\n      <div class=\"th_inner options\">Mode</div>\n    </th>\n    <th class=\"ctxmenu\"></th>\n    <th>\n      <div class=\"th_inner desc\">Comment</div>\n    </th>\n    <th><div class=\"th_inner blank\">&nbsp;</div></th>\n  </tr>\n</thead>\n<tbody></tbody>")
  });

  marginBottom = 0;

  resizeTimer = false;

  windowOnResize = function() {
    if (resizeTimer) {
      clearTimeout(resizeTimer);
    }
    return resizeTimer = setTimeout((function() {
      var tableHeight;
      tableHeight = window.innerHeight - document.querySelector(".header").offsetHeight - marginBottom;
      document.querySelector(".fixed-table-container").style.pixelHeight = tableHeight;
      $(".fixed-table-container-inner").getNiceScroll().resize();
      return $(".result_outer").getNiceScroll().resize();
    }), 200);
  };

  startEdit = function() {
    return andy.startEdit();
  };

  endEdit = function() {
    return andy.endEdit();
  };

  andy = chrome.extension.getBackgroundPage().andy;

  $ = jQuery;

  $(function() {
    var bookmarkOptionsView, ctxMenuFolderSet, keyConfigSet, saveData;
    keyCodes = andy.getKeyCodes();
    scHelp = andy.getScHelp();
    scHelpSect = andy.getScHelpSect();
    saveData = andy.local;
    headerView = new HeaderView({
      model: new Config(saveData.config)
    });
    headerView.render();
    keyConfigSet = new KeyConfigSet();
    keyConfigSetView = new KeyConfigSetView({
      model: new Config(saveData.config),
      collection: keyConfigSet
    });
    bookmarksView = new BookmarksView({});
    bookmarkOptionsView = new BookmarkOptionsView({});
    commandsView = new CommandsView({});
    commandOptionsView = new CommandOptionsView({});
    ctxMenuFolderSet = new CtxMenuFolderSet();
    ctxMenuOptionsView = new CtxMenuOptionsView({
      collection: ctxMenuFolderSet
    });
    ctxMenuManagerView = new CtxMenuManagerView({
      collection: ctxMenuFolderSet
    });
    headerView.on("clickAddKeyConfig", keyConfigSetView.onClickAddKeyConfig, keyConfigSetView);
    headerView.on("changeSelKbd", keyConfigSetView.onChangeSelKbd, keyConfigSetView);
    ctxMenuOptionsView.on("getCtxMenues", keyConfigSetView.onGetCtxMenues, keyConfigSetView);
    ctxMenuOptionsView.on("remakeCtxMenu", keyConfigSetView.onRemakeCtxMenu, keyConfigSetView);
    ctxMenuManagerView.on("getCtxMenues", keyConfigSetView.onGetCtxMenues, keyConfigSetView);
    ctxMenuManagerView.on("remakeCtxMenu", keyConfigSetView.onRemakeCtxMenu, keyConfigSetView);
    keyConfigSet.on("getCtxMenuContexts", ctxMenuManagerView.onGetCtxMenuContexts, ctxMenuManagerView);
    ctxMenuManagerView.on("enterCtxMenuSelMode", keyConfigSetView.onEnterCtxMenuSelMode, keyConfigSetView);
    ctxMenuManagerView.on("enterCtxMenuSelMode", headerView.onEnterCtxMenuSelMode, headerView);
    ctxMenuManagerView.on("leaveCtxMenuSelMode", keyConfigSetView.onLeaveCtxMenuSelMode, keyConfigSetView);
    ctxMenuManagerView.on("leaveCtxMenuSelMode", headerView.onLeaveCtxMenuSelMode, headerView);
    ctxMenuManagerView.on("triggerEventSelected", keyConfigSetView.onTriggerEventSelected, keyConfigSetView);
    ctxMenuManagerView.on("setCtxMenus", keyConfigSetView.onSetCtxMenus, keyConfigSetView);
    commandOptionsView.on("getEditerSize", keyConfigSetView.onGetEditerSize, keyConfigSetView);
    commandOptionsView.on("setEditerSize", keyConfigSetView.onSetEditerSize, keyConfigSetView);
    ctxMenuFolderSet.reset(saveData.ctxMenuFolderSet);
    keyConfigSetView.render(saveData.keyConfigSet);
    chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
      switch (request.action) {
        case "kbdEvent":
          return keyConfigSetView.collection.trigger("kbdEvent", request.value);
        case "saveConfig":
          return andy.saveConfig(keyConfigSetView.getSaveData());
      }
    });
    $(window).on("unload", function() {
      return andy.saveConfig(keyConfigSetView.getSaveData());
    }).on("resize", function() {
      return windowOnResize();
    }).on("click", function() {
      return lastFocused = null;
    });
    return windowOnResize();
  });

}).call(this);
