// Generated by CoffeeScript 1.6.3
(function() {
  var $, BookmarkOptionsView, BookmarksView, CommandOptionsView, CommandsView, Config, CtxMenuManagerView, CtxMenuOptionsView, EditableBaseView, ExplorerBaseView, HeaderView, KeyConfig, KeyConfigSet, KeyConfigSetView, KeyConfigView, PopupBaseView, WebFontConfig, andy, bmOpenMode, bookmarksView, catnames, commandOptionsView, commandsDisp, commandsView, ctxMenuOptionsView, decodeKbdEvent, endEdit, escape, gMaxItems, keyCodes, keyConfigSetView, keys, lastFocused, marginBottom, modeDisp, modifierInits, modifierKeys, resizeTimer, scHelp, scHelpSect, startEdit, tmplCtxMenus, transKbdEvent, windowOnResize, _ref, _ref1, _ref2, _ref3,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  keyConfigSetView = null;

  commandsView = null;

  bookmarksView = null;

  commandOptionsView = null;

  ctxMenuOptionsView = null;

  PopupBaseView = Backbone.View.extend({
    initialize: function(options) {
      return keyConfigSetView.on("showPopup", this.onShowPopup, this);
    },
    events: {
      "submit form": "onSubmitForm",
      "click  .icon-remove": "onClickIconRemove"
    },
    render: function() {},
    onSubmitForm: function() {},
    onShowPopup: function(name, model, options) {
      var shortcut,
        _this = this;
      if (name !== this.name) {
        return false;
      }
      this.model = model;
      this.options = options;
      shortcut = decodeKbdEvent(model.get("new"));
      this.$(".shortcut").html(_.map(shortcut.split(" + "), function(s) {
        return "<span>" + s + "</span>";
      }).join("+"));
      this.render();
      this.$el.show().draggable({
        cursor: "move",
        delay: 200,
        cancel: "input,textarea,button,select,option,.bookmarkPanel",
        stop: function() {
          return _this.onStopDrag();
        }
      });
      this.el.style.pixelLeft = Math.round((window.innerWidth - this.el.offsetWidth) / 2);
      this.el.style.pixelTop = Math.round((window.innerHeight - this.el.offsetHeight) / 2);
      this.$(".caption").focus();
      return $(".backscreen").show();
    },
    onStopDrag: function() {},
    onClickIconRemove: function() {
      return this.hidePopup();
    },
    hidePopup: function() {
      $(".backscreen").hide();
      return this.$el.hide();
    },
    tmplHelp: _.template("<a href=\"helpview.html#<%=name%>\" target=\"_blank\" class=\"help\" title=\"help\">\n  <i class=\"icon-question-sign\" title=\"Help\"></i>\n</a>")
  });

  EditableBaseView = (function(_super) {
    __extends(EditableBaseView, _super);

    function EditableBaseView() {
      _ref = EditableBaseView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    EditableBaseView.prototype.onShowPopup = function(name, model, options) {
      if (!EditableBaseView.__super__.onShowPopup.call(this, name, model, options)) {
        return false;
      }
      return startEdit();
    };

    EditableBaseView.prototype.hidePopup = function() {
      endEdit();
      return EditableBaseView.__super__.hidePopup.call(this);
    };

    return EditableBaseView;

  })(PopupBaseView);

  ExplorerBaseView = (function(_super) {
    __extends(ExplorerBaseView, _super);

    ExplorerBaseView.prototype.events = _.extend({
      "click .title": "onClickFolder",
      "click .expand-icon": "onClickExpandIcon",
      "click .expandAll": "onClickExpandAll"
    }, PopupBaseView.prototype.events);

    function ExplorerBaseView(options) {
      var ctx;
      ExplorerBaseView.__super__.constructor.call(this, options);
      ctx = document.getCSSCanvasContext('2d', 'triangle', 8, 5.5);
      ctx.fillStyle = '#000000';
      ctx.translate(.5, .5);
      ctx.beginPath();
      ctx.moveTo(0, 0);
      ctx.lineTo(0, 1);
      ctx.lineTo(3.5, 4.5);
      ctx.lineTo(7, 1);
      ctx.lineTo(7, 0);
      ctx.closePath();
      ctx.fill();
      ctx.stroke();
      this.$(".result_outer").niceScroll({
        cursorwidth: 12,
        cursorborderradius: 6,
        smoothscroll: true,
        cursoropacitymin: .1,
        cursoropacitymax: .6
      });
      this.elResult$ = this.$(".result");
    }

    ExplorerBaseView.prototype.onShowPopup = function(name, model, options) {
      if (!ExplorerBaseView.__super__.onShowPopup.call(this, name, model, options)) {
        return false;
      }
      return this.$(".result_outer").getNiceScroll().show();
    };

    ExplorerBaseView.prototype.onStopDrag = function() {
      return this.$(".result_outer").getNiceScroll().resize();
    };

    ExplorerBaseView.prototype.hidePopup = function() {
      this.$(".result_outer").getNiceScroll().hide();
      return ExplorerBaseView.__super__.hidePopup.call(this);
    };

    ExplorerBaseView.prototype.onClickFolder = function(event) {
      var target$, visible;
      visible = (target$ = $(event.currentTarget).parent()).hasClass("opened");
      if (visible) {
        target$.removeClass("opened expanded");
      } else {
        target$.addClass("opened expanded");
      }
      windowOnResize();
      return event.stopPropagation();
    };

    ExplorerBaseView.prototype.onClickExpandIcon = function(event) {
      var expanded, target$;
      expanded = (target$ = $(event.currentTarget).parent()).hasClass("expanded");
      if (expanded) {
        target$.removeClass("expanded");
      } else {
        target$.addClass("expanded");
      }
      windowOnResize();
      return event.stopPropagation();
    };

    ExplorerBaseView.prototype.onClickExpandAll = function() {
      if (this.$(".expandAll").is(":checked")) {
        this.$(".folder").addClass("opened expanded");
      } else {
        this.$(".folder").removeClass("opened expanded");
      }
      return windowOnResize();
    };

    return ExplorerBaseView;

  })(PopupBaseView);

  commandsDisp = {
    createTab: ["tab", "Create new tab"],
    createTabBG: ["tab", "Create new tab in background"],
    moveTabLeft: ["tab", "Move current tab left"],
    moveTabRight: ["tab", "Move current tab right"],
    moveTabFirst: ["tab", "Move current tab to first position"],
    moveTabLast: ["tab", "Move current tab to last position"],
    closeOtherTabs: ["tab", "Close other tabs"],
    closeTabsLeft: ["tab", "Close tabs to the left"],
    closeTabsRight: ["tab", "Close tabs to the right"],
    duplicateTab: ["tab", "Duplicate current tab"],
    pinTab: ["tab", "Pin/Unpin current tab"],
    detachTab: ["tab", "Detach current tab"],
    attachTab: ["tab", "Attach current tab to the next window"],
    switchPrevWin: ["win", "Switch to the previous window"],
    switchNextWin: ["win", "Switch to the next window"],
    closeOtherWins: ["win", "Close other windows"],
    clearCache: ["clr", "Clear the browser's cache"],
    clearCookiesAll: ["clr", "Clear the browser's cookies and site data"],
    clearCookies: ["clr", "Clear all cookies for the current domain"],
    pasteText: ["custom", "Paste fixed text", [], "Clip"],
    insertCSS: [
      "custom", "Inject CSS", [
        {
          value: "allFrames",
          caption: "All frames"
        }
      ], "CSS"
    ],
    execJS: [
      "custom", "Inject script", [
        {
          value: "allFrames",
          caption: "All frames"
        }, {
          value: "useUtilObj",
          caption: "Use utility object"
        }
      ], "JS"
    ]
  };

  catnames = {
    tab: "Tab commands",
    win: "Window commands",
    clr: "Browsing data commands",
    clip: "Clipboard commands",
    custom: "Other"
  };

  CommandOptionsView = (function(_super) {
    __extends(CommandOptionsView, _super);

    CommandOptionsView.prototype.name = "commandOptions";

    CommandOptionsView.prototype.el = ".commandOptions";

    function CommandOptionsView(options) {
      CommandOptionsView.__super__.constructor.call(this, options);
      commandsView.on("showPopup", this.onShowPopup, this);
    }

    CommandOptionsView.prototype.render = function() {
      var commandName, commandOption, content$,
        _this = this;
      content$ = this.$(".content").css("height", "auto");
      if ((commandName = this.options.name) === "clearHistoryS") {
        content$.attr("rows", "1");
      } else {
        content$.attr("rows", "10");
      }
      this.$(".command").html(commandsDisp[commandName][1]);
      this.$(".caption").val(this.options.caption);
      content$.val(this.options.content);
      commandOption = this.$(".inputs").empty();
      commandsDisp[commandName][2].forEach(function(option) {
        option.checked = "";
        if (_this.options[option.value]) {
          option.checked = "checked";
        }
        return commandOption.append(_this.tmplOptions(option));
      });
      return this.$el.append(this.tmplHelp(this));
    };

    CommandOptionsView.prototype.onShowPopup = function(name, model, options) {
      if (!CommandOptionsView.__super__.onShowPopup.call(this, name, model, options)) {
        return;
      }
      if (this.options.content) {
        return this.$(".content").focus()[0].setSelectionRange(0, 0);
      } else {
        return this.$(".caption").focus();
      }
    };

    CommandOptionsView.prototype.onSubmitForm = function() {
      var caption, content, options,
        _this = this;
      if ((content = this.$(".content").val()) !== "") {
        options = {};
        $.each(this.$(".inputs input[type='checkbox']"), function(i, option) {
          options[option.value] = option.checked;
        });
        if (!(caption = this.$(".caption").val())) {
          caption = content.split("\n")[0];
        }
        this.model.set({
          "command": _.extend({
            name: this.options.name,
            caption: caption,
            content: content
          }, options)
        }, {
          silent: true
        }).trigger("change:command");
        this.hidePopup();
      }
      return false;
    };

    CommandOptionsView.prototype.tmplOptions = _.template("<label>\n  <input type=\"checkbox\" value=\"<%=value%>\" <%=checked%>> <%=caption%>\n</label><br>");

    return CommandOptionsView;

  })(EditableBaseView);

  CommandsView = (function(_super) {
    __extends(CommandsView, _super);

    function CommandsView() {
      _ref1 = CommandsView.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    CommandsView.prototype.name = "command";

    CommandsView.prototype.el = ".commands";

    CommandsView.prototype.render = function() {
      var categories, key, target$;
      target$ = this.$(".commandRadios");
      target$.empty();
      categories = [];
      for (key in commandsDisp) {
        categories.push(commandsDisp[key][0]);
      }
      categories = _.unique(categories);
      categories.forEach(function(cat) {
        return target$.append("<div class=\"cat" + cat + "\"><div class=\"catname\">" + catnames[cat] + "</div>");
      });
      for (key in commandsDisp) {
        target$.find(".cat" + commandsDisp[key][0]).append(this.tmplItem({
          key: key,
          value: commandsDisp[key][1]
        }));
      }
      return this;
    };

    CommandsView.prototype.onShowPopup = function(name, model, options) {
      if (!CommandsView.__super__.onShowPopup.call(this, name, model)) {
        return;
      }
      if (options) {
        this.$(".radioCommand").val([options.name]);
      }
      return this.$el.append(this.tmplHelp(this));
    };

    CommandsView.prototype.onSubmitForm = function() {
      var command;
      if (command = this.$(".radioCommand:checked").val()) {
        this.hidePopup();
        if (commandsDisp[command][2]) {
          this.trigger("showPopup", "commandOptions", this.model, {
            name: command
          });
        } else {
          this.model.set({
            "command": {
              name: command
            }
          }, {
            silent: true
          }).trigger("change:command");
        }
      }
      return false;
    };

    CommandsView.prototype.tmplItem = _.template("<div>\n  <label>\n    <input type=\"radio\" name=\"radioCommand\" class=\"radioCommand\" value=\"<%=key%>\">\n    <%=value%>\n  </label>\n</div>");

    return CommandsView;

  })(PopupBaseView);

  BookmarkOptionsView = (function(_super) {
    __extends(BookmarkOptionsView, _super);

    BookmarkOptionsView.prototype.name = "bookmarkOptions";

    BookmarkOptionsView.prototype.el = ".bookmarkOptions";

    BookmarkOptionsView.prototype.events = _.extend({
      "click input[value='findtab']": "onClickFindTab",
      "change input[name='openmode']:radio": "onChangeOpenmode"
    }, PopupBaseView.prototype.events);

    function BookmarkOptionsView(options) {
      BookmarkOptionsView.__super__.constructor.call(this, options);
      bookmarksView.on("showPopup", this.onShowPopup, this);
    }

    BookmarkOptionsView.prototype.render = function() {
      var elFindtab, findtab;
      BookmarkOptionsView.__super__.render.call(this);
      this.$(".bookmark").css("background-image", "-webkit-image-set(url(chrome://favicon/size/16@1x/" + this.options.url + ") 1x)").text(this.options.title);
      this.$(".url").text(this.options.url);
      this.$(".findStr").val(this.options.findStr || this.options.url);
      this.$("input[value='" + (this.options.openmode || 'current') + "']")[0].checked = true;
      (elFindtab = this.$("input[value='findtab']")[0]).checked = (findtab = this.options.findtab) === void 0 ? true : findtab;
      this.onClickFindTab({
        currentTarget: elFindtab
      });
      return this.$el.append(this.tmplHelp(this));
    };

    BookmarkOptionsView.prototype.onSubmitForm = function() {
      var options,
        _this = this;
      options = {};
      $.each(this.$("form input[type='checkbox']"), function(i, option) {
        options[option.value] = option.checked;
      });
      options.findtab = this.$("input[value='findtab']").is(":checked");
      options.openmode = this.$("input[name='openmode']:checked").attr("value");
      options.findStr = this.$(".findStr").val();
      this.model.set({
        "bookmark": _.extend(this.options, options)
      }, {
        silent: true
      }).trigger("change:bookmark");
      this.hidePopup();
      return false;
    };

    BookmarkOptionsView.prototype.onChangeOpenmode = function(event) {
      var chkFindtab$, openmode;
      openmode = this.$("input[name='openmode']:checked").val();
      chkFindtab$ = this.$("input[value='findtab']");
      if (openmode === "findonly") {
        chkFindtab$.attr("disabled", "disabled")[0].checked = true;
      } else {
        chkFindtab$.removeAttr("disabled");
      }
      return this.onClickFindTab({
        currentTarget: {
          checked: chkFindtab$[0].checked
        }
      });
    };

    BookmarkOptionsView.prototype.onClickFindTab = function(event) {
      if (event.currentTarget.checked) {
        return this.$(".findStr").removeAttr("disabled");
      } else {
        return this.$(".findStr").attr("disabled", "disabled").blur();
      }
    };

    return BookmarkOptionsView;

  })(EditableBaseView);

  BookmarksView = (function(_super) {
    __extends(BookmarksView, _super);

    function BookmarksView() {
      _ref2 = BookmarksView.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    BookmarksView.prototype.name = "bookmark";

    BookmarksView.prototype.el = ".bookmarks";

    BookmarksView.prototype.events = _.extend({
      "click  a": "onClickBookmark"
    }, ExplorerBaseView.prototype.events);

    BookmarksView.prototype.render = function() {
      var height;
      height = window.innerHeight - 60;
      this.$(".result_outer").height(height - 35);
      this.$el.height(height);
      if (this.$(".result").children().length === 0) {
        this.onSubmitForm();
      }
      return this;
    };

    BookmarksView.prototype.onShowPopup = function(name, model) {
      var target;
      if (!BookmarksView.__super__.onShowPopup.call(this, name, model)) {
        return;
      }
      if ((target = this.$("input.query")).val()) {
        return target.focus();
      }
    };

    BookmarksView.prototype.onSubmitForm = function() {
      var query, state,
        _this = this;
      this.$(".result").empty();
      query = this.$("input.query").focus().val();
      if (query) {
        this.$(".expandAll")[0].checked = true;
      }
      state = this.$(".expandAll").is(":checked") ? "opened expanded" : "";
      chrome.bookmarks.getTree(function(treeNode) {
        var recent;
        treeNode.forEach(function(node) {
          return _this.digBookmarks(node, _this.elResult$, query, 0, state);
        });
        _this.elResult$.append(recent = $(_this.tmplFolder({
          "title": "Recent",
          "state": state,
          "indent": 0
        })));
        recent.find(".title").prepend("<img src=\"images/star.png\">");
        return chrome.bookmarks.getRecent(50, function(treeNode) {
          return treeNode.forEach(function(node) {
            return _this.digBookmarks(node, recent, query, 1, state);
          });
        });
      });
      return false;
    };

    BookmarksView.prototype.digBookmarks = function(node, parent, query, indent, state) {
      var newParent,
        _this = this;
      if (node.title) {
        node.state = state;
        if (node.children) {
          node.indent = indent;
          parent.append(newParent = $(this.tmplFolder(node)));
          parent = newParent;
        } else {
          if (!query || (node.title + " " + node.url).toUpperCase().indexOf(query.toUpperCase()) > -1) {
            node.indent = indent + 1;
            parent.append($(this.tmplLink(node)));
          }
        }
      } else {
        indent--;
      }
      if (node.children) {
        parent.parent().addClass("hasFolder");
        return node.children.forEach(function(child) {
          return _this.digBookmarks(child, parent, query, indent + 1, state);
        });
      }
    };

    BookmarksView.prototype.onClickBookmark = function(event) {
      var target;
      this.hidePopup();
      target = $(event.currentTarget);
      this.trigger("showPopup", "bookmarkOptions", this.model, {
        title: target.text(),
        url: target.attr("title"),
        bmId: target.attr("data-id")
      });
      return false;
    };

    BookmarksView.prototype.tmplFolder = _.template("<div class=\"folder <%=state%>\" style=\"text-indent:<%=indent%>em\">\n  <span class=\"expand-icon\"></span><span class=\"title\"><%=title%></span>\n</div>");

    BookmarksView.prototype.tmplLink = _.template("<div class=\"link\" style=\"text-indent:<%=indent%>em;\">\n  <a href=\"#\" title=\"<%=url%>\" data-id=\"<%=id%>\" style=\"background-image:-webkit-image-set(url('chrome://favicon/size/16@1x/<%=url%>') 1x);\"><%=title%></a>\n</div>");

    return BookmarksView;

  })(ExplorerBaseView);

  tmplCtxMenus = {
    page: ["Return the page URL", "icon-file"],
    selection: ["Return the selection text", "icon-font"],
    editable: ["Return the page URL or selection text", "icon-edit"],
    link: ["Return the link URL", "icon-link"],
    image: ["Return the image URL", "icon-picture"],
    all: ["Return any of the above", "icon-asterisk"]
  };

  CtxMenuOptionsView = (function(_super) {
    __extends(CtxMenuOptionsView, _super);

    function CtxMenuOptionsView() {
      _ref3 = CtxMenuOptionsView.__super__.constructor.apply(this, arguments);
      return _ref3;
    }

    CtxMenuOptionsView.prototype.name = "ctxMenuOptions";

    CtxMenuOptionsView.prototype.el = ".ctxMenuOptions";

    CtxMenuOptionsView.prototype.events = _.extend({
      "click  .done,.delete": "onClickSubmit",
      "change .selectParent": "onChangeSelectParent",
      "click  .selectParent": "onClickSelectParent",
      "focus  .parentName": "onFocusParentName",
      "blur   .parentName": "onBlurParentName"
    }, PopupBaseView.prototype.events);

    CtxMenuOptionsView.prototype.render = function() {
      var container, lastParent, parent, selectParent$, _ref4, _ref5, _ref6;
      this.ctxMenu = this.model.get("ctxMenu");
      this.$(".caption").val(((_ref4 = this.ctxMenu) != null ? _ref4.caption : void 0) || this.options.desc);
      this.$el.append(this.tmplHelp(this));
      this.$("input[value='" + (((_ref5 = this.ctxMenu) != null ? _ref5.contexts : void 0) || 'page') + "']")[0].checked = true;
      if (this.ctxMenu) {
        this.$(".delete").addClass("red").removeClass("disabled").removeAttr("disabled");
      } else {
        this.$(".delete").removeClass("red").addClass("disabled").attr("disabled", "disabled");
      }
      lastParent = (selectParent$ = this.$(".selectParent")).val();
      this.trigger("getCtxMenuParents", container = {});
      selectParent$.html(this.tmplParentMenu);
      container.parents.forEach(function(parentName) {
        return selectParent$.append("<option value=\"" + parentName + "\">" + parentName + "</option>");
      });
      if (parent = (_ref6 = this.ctxMenu) != null ? _ref6.parent : void 0) {
        selectParent$.val(parent);
      } else if (__indexOf.call(container.parents, lastParent) >= 0) {
        selectParent$.val(lastParent);
      } else {
        selectParent$.val("root");
      }
      return this.$(".parentName").val("").hide();
    };

    CtxMenuOptionsView.prototype.onChangeSelectParent = function(event) {
      if (event.currentTarget.value !== "new") {
        return this.$(".parentName").hide();
      } else {
        return this.$(".parentName").show().focus();
      }
    };

    CtxMenuOptionsView.prototype.onClickSelectParent = function(event) {
      return event.preventDefault();
    };

    CtxMenuOptionsView.prototype.onFocusParentName = function(event) {
      return this.$(".selectParent").addClass("focus");
    };

    CtxMenuOptionsView.prototype.onBlurParentName = function() {
      return this.$(".selectParent").removeClass("focus");
    };

    CtxMenuOptionsView.prototype.onSubmitForm = function() {
      return false;
    };

    CtxMenuOptionsView.prototype.setContextMenu = function(actionType, id, caption, contexts, parentName, callback) {
      var sendData;
      if (callback == null) {
        callback = function() {};
      }
      sendData = {
        type: actionType,
        id: id,
        action: "aboutCtxMenu"
      };
      if (caption && contexts) {
        sendData.caption = caption;
        sendData.contexts = contexts;
        sendData.parent = parentName;
      }
      return chrome.runtime.sendMessage(sendData, callback);
    };

    CtxMenuOptionsView.prototype.pause = function(id) {
      return this.setContextMenu("update pause", id);
    };

    CtxMenuOptionsView.prototype.resume = function(id) {
      return this.setContextMenu("update", id);
    };

    CtxMenuOptionsView.prototype.onClickSubmit = function(event) {
      var caption, dfd, menutype, parentName,
        _this = this;
      if ((parentName = this.$(".selectParent").val()) === "new") {
        parentName = $.trim(this.$(".parentName").val());
      }
      if (parentName === "") {
        return;
      }
      if ((caption = this.$(".caption").val()) !== "") {
        menutype = this.$("input[name='menutype']:checked").attr("value");
        if (/delete/.test(event != null ? event.currentTarget.className : void 0)) {
          if (!confirm("Are you sure you want to delete this Context Menu?")) {
            return false;
          }
          this.model.unset("ctxMenu");
        } else {
          this.model.set("ctxMenu", {
            caption: caption,
            contexts: menutype,
            parent: parentName
          });
        }
        (dfd = $.Deferred()).promise();
        this.trigger("remakeCtxMenu", {
          dfd: dfd
        });
        dfd.done(function() {
          _this.hidePopup();
          if (_this.$("input[value='chkShowManager']").is(":checked")) {
            return _this.trigger("showPopup", "ctxMenuManager", _this.model);
          }
        });
      }
      return false;
    };

    CtxMenuOptionsView.prototype.tmplParentMenu = "<option value=\"root\">None(Root)</option>\n<option value=\"new\">Create under new parent menu...</option>";

    CtxMenuOptionsView.prototype.tmplContexts = _.template("<label>\n  <input type=\"radio\" name=\"menutype\" value=\"<%=value%>\"> <strong><%=caption%></strong> - <%=desc%>\n</label><br>");

    return CtxMenuOptionsView;

  })(EditableBaseView);

  CtxMenuManagerView = (function(_super) {
    __extends(CtxMenuManagerView, _super);

    CtxMenuManagerView.prototype.name = "ctxMenuManager";

    CtxMenuManagerView.prototype.el = ".ctxMenuManager";

    CtxMenuManagerView.prototype.events = _.extend({
      "click  a": "onClickBookmark"
    }, ExplorerBaseView.prototype.events);

    function CtxMenuManagerView(options) {
      CtxMenuManagerView.__super__.constructor.call(this, options);
      ctxMenuOptionsView.on("showPopup", this.onShowPopup, this);
    }

    CtxMenuManagerView.prototype.render = function() {
      var height;
      height = window.innerHeight - 60;
      this.$(".result_outer").height(height - 35);
      this.$el.height(height);
      this.setContextMenu();
      return this;
    };

    CtxMenuManagerView.prototype.onShowPopup = function(name, model) {
      if (!CtxMenuManagerView.__super__.onShowPopup.call(this, name, model)) {

      }
    };

    CtxMenuManagerView.prototype.setContextMenu = function() {
      var container, context$, key,
        _this = this;
      this.$(".result").empty();
      this.trigger("getCtxMenues", container = {});
      for (key in tmplCtxMenus) {
        if (_.find(container.ctxMenus, function(ctxMenu) {
          return ctxMenu.contexts === key;
        })) {
          this.elResult$.append(context$ = $(this.tmplContexts({
            "contexts": key,
            "dispname": key.substring(0, 1).toUpperCase() + key.substring(1),
            "icon": tmplCtxMenus[key][1]
          })));
          container.parents.forEach(function(parentMenu) {
            var folder$;
            context$.append(folder$ = $(_this.tmplFolder({
              "id": parentMenu.id
            })));
            return folder$[0].ctxParent = parentMenu.id;
          });
        }
      }
      return container.ctxMenus.forEach(function(ctxMenu) {
        return $.each(_this.$("." + ctxMenu.contexts + " .folder"), function(i, el) {
          if (el.ctxParent === ctxMenu.parent) {
            return $(el).append(_this.tmplMenuItem({
              id: ctxMenu.id,
              caption: ctxMenu.caption
            }));
          }
        });
      });
    };

    CtxMenuManagerView.prototype.tmplContexts = _.template("<div class=\"contexts <%=contexts%>\">\n  <span class=\"expand-icon\"></span><span class=\"contexts\"><i class=\"<%=icon%> contextIcon\"></i><%=dispname%></span>\n</div>");

    CtxMenuManagerView.prototype.tmplFolder = _.template("<div class=\"folder parent opened expanded\">\n  <span class=\"expand-icon\"></span><span class=\"title\"><%=id%></span>\n</div>");

    CtxMenuManagerView.prototype.tmplMenuItem = _.template("<div class=\"ctxMenuItem\" id=\"<%=id%>\"><%=caption%></div>");

    return CtxMenuManagerView;

  })(ExplorerBaseView);

  gMaxItems = 100;

  lastFocused = null;

  keyCodes = {};

  scHelp = null;

  scHelpSect = null;

  keys = null;

  WebFontConfig = {
    google: {
      families: ['Noto+Sans::latin']
    }
  };

  modeDisp = {
    remap: ["Remap", "icon-random"],
    command: ["Command...", "icon-cog"],
    bookmark: ["Bookmark...", "icon-bookmark"],
    disabled: ["Disabled", "icon-ban-circle"],
    through: ["Pause", "icon-pause", "nodisp"]
  };

  bmOpenMode = {
    current: "Open in current tab",
    newtab: "Open in new tab",
    newwin: "Open in new window",
    incognito: "Open in incognito window"
  };

  escape = function(html) {
    var entity;
    entity = {
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;"
    };
    return html.replace(/[&<>]/g, function(match) {
      return entity[match];
    });
  };

  modifierKeys = ["Ctrl", "Alt", "Shift", "Win", "MouseL", "MouseR", "MouseM"];

  modifierInits = ["c", "a", "s", "w"];

  decodeKbdEvent = function(value) {
    var keyCombo, keyIdentifier, modifiers, scanCode;
    modifiers = parseInt(value.substring(0, 2), 16);
    scanCode = value.substring(2);
    if (keyIdentifier = keys[scanCode]) {
      keyCombo = [];
      if (modifiers & 1) {
        keyCombo.push(modifierKeys[0]);
      }
      if (modifiers & 4) {
        keyCombo.push(modifierKeys[2]);
      }
      if (modifiers & 2) {
        keyCombo.push(modifierKeys[1]);
      }
      if (modifiers & 8) {
        keyCombo.push(modifierKeys[3]);
      }
      if (modifiers & 4) {
        keyCombo.push(keyIdentifier[1] || keyIdentifier[0]);
      } else {
        keyCombo.push(keyIdentifier[0]);
      }
      return keyCombo.join(" + ");
    }
  };

  transKbdEvent = function(value) {
    var i, keyCombo, keyIdenfiers, modifiers, scanCode, _i, _ref4;
    modifiers = parseInt(value.substring(0, 2), 16);
    keyCombo = [];
    for (i = _i = 0, _ref4 = modifierInits.length; 0 <= _ref4 ? _i < _ref4 : _i > _ref4; i = 0 <= _ref4 ? ++_i : --_i) {
      if (modifiers & Math.pow(2, i)) {
        keyCombo.push(modifierInits[i]);
      }
    }
    scanCode = value.substring(2);
    keyIdenfiers = keys[scanCode];
    return "[" + keyCombo.join("") + "]" + keyIdenfiers[0];
  };

  HeaderView = Backbone.View.extend({
    scHelpUrl: "https://support.google.com/chrome/answer/157179?hl=",
    el: "div.header",
    events: {
      "click button.addKeyConfig": "onClickAddKeyConfig",
      "change select.kbdtype": "onChangeSelKbd"
    },
    initialize: function(options) {
      var kbdtype, selectKbd$,
        _this = this;
      keys = keyCodes[kbdtype = this.model.get("kbdtype")].keys;
      selectKbd$ = this.$("select.kbdtype");
      $.each(keyCodes, function(key, item) {
        return selectKbd$.append("<option value=\"" + key + "\">" + item.name + "</option>");
      });
      selectKbd$.val(kbdtype);
      return this.setScHelp(kbdtype);
    },
    onClickAddKeyConfig: function(event) {
      return this.trigger("clickAddKeyConfig", event);
    },
    onChangeSelKbd: function(event) {
      this.trigger("changeSelKbd", event);
      return this.setScHelp(this.$("select.kbdtype").val());
    },
    setScHelp: function(kbdtype) {
      return this.$(".scHelp").text("ショートカットキー一覧").attr("href", this.scHelpUrl + "ja");
    },
    setScHelp0: function(kbdtype) {
      if (kbdtype === "JP") {
        return this.$(".scHelp").text("ショートカットキー一覧").attr("href", this.scHelpUrl + "ja");
      } else {
        return this.$(".scHelp").text("Keyboard shortcuts").attr("href", this.scHelpUrl + "en");
      }
    }
  });

  Config = Backbone.Model.extend({});

  KeyConfig = Backbone.Model.extend({
    idAttribute: "new",
    defaults: {
      mode: "remap"
    }
  });

  KeyConfigSet = Backbone.Collection.extend({
    model: KeyConfig
  });

  KeyConfigView = Backbone.View.extend({
    kbdtype: null,
    optionKeys: [],
    events: {
      "click .origin,.new": "onClickInput",
      "click div.mode": "onClickMode",
      "click .selectMode div": "onChangeMode",
      "click div.edit": "onClickEdit",
      "click div.copySC": "onClickCopySC",
      "click div.ctxmenu": "onClickCtxMenu",
      "click div.pause": "onClickPause",
      "click div.resume": "onClickResume",
      "click div.delete": "onClickRemove",
      "click input.memo": "onClickInputMemo",
      "click button.cog": "onClickCog",
      "focus .new,.origin": "onFocusKeyInput",
      "keydown .origin": "onKeydownOrigin",
      "keydown .new": "onKeydownNew",
      "submit  .memo": "onSubmitMemo",
      "blur  .selectMode": "onBlurSelectMode",
      "blur  .selectCog": "onBlurSelectCog",
      "blur  input.memo": "onBlurInputMemo"
    },
    initialize: function(options) {
      this.optionKeys = _.keys(modeDisp);
      this.model.on({
        "change:bookmark": this.onChangeBookmark,
        "change:command": this.onChangeCommand,
        "change:ctxMenu": this.onChangeCtxmenu,
        "setFocus": this.onClickInput,
        "remove": this.onRemove
      }, this);
      return this.model.collection.on({
        "kbdEvent": this.onKbdEvent,
        "changeKbd": this.onChangeKbd,
        "updateOrder": this.onUpdateOrder
      }, this);
    },
    render: function(kbdtype) {
      var mode;
      this.setElement(this.template({
        options: modeDisp
      }));
      mode = this.model.get("mode");
      if (!this.setKbdValue(this.$(".new"), this.model.id)) {
        this.state = "invalid";
      }
      this.setKbdValue(this.$(".origin"), this.model.get("origin"));
      this.kbdtype = kbdtype;
      this.onChangeMode(null, mode);
      return this;
    },
    onChangeBookmark: function() {
      return this.onChangeMode(null, "bookmark");
    },
    onChangeCommand: function() {
      return this.onChangeMode(null, "command");
    },
    onChangeCtxmenu: function() {
      var ctxMenu;
      if (ctxMenu = this.model.get("ctxMenu")) {
        this.$("td.ctxmenu").html("<div class=\"ctxmenu-icon\" title=\"Context menu for " + ctxMenu.contexts + "\nTitle: " + ctxMenu.caption + "\"><i class=\"" + tmplCtxMenus[ctxMenu.contexts][1] + "\"></i></div>");
        this.$("div.ctxmenu")[0].childNodes[1].nodeValue = " Edit context menu...";
      } else if (this.model.get("mode") !== "disabled") {
        this.$("td.ctxmenu").empty();
        this.$("div.ctxmenu")[0].childNodes[1].nodeValue = " Create context menu...";
      }
      return this.trigger("resizeInput");
    },
    onRemove: function() {
      this.model.off(null, null, this);
      this.off(null, null, null);
      return this.remove();
    },
    onKbdEvent: function(value) {
      var input$, scanCode;
      input$ = this.$("div:focus");
      if (input$.length > 0) {
        if (input$.hasClass("new")) {
          if (this.model.id !== value && this.model.collection.findWhere({
            "new": value
          })) {
            $("#tiptip_content").text("\"" + (decodeKbdEvent(value)) + "\" is already exists.");
            input$.tipTip();
            return;
          }
        } else {
          scanCode = ~~value.substring(2);
          if (scanCode > 0x200 || scanCode === 0x15D) {
            return;
          }
        }
        this.setKbdValue(input$, value);
        this.model.set(input$[0].className.match(/(new|origin)/)[0], value);
        this.setDesc();
        return this.trigger("resizeInput");
      }
    },
    onChangeKbd: function(kbdtype) {
      this.kbdtype = kbdtype;
      this.setKbdValue(this.$(".new"), this.model.id);
      this.setKbdValue(this.$(".origin"), this.model.get("origin"));
      return this.setDesc();
    },
    onUpdateOrder: function() {
      return this.model.set("ordernum", this.$el.parent().children().index(this.$el));
    },
    onKeydownOrigin: function(event) {
      var i, keyname, keynames, scCode, scanCode, _i, _ref4;
      if (keynames = keyIdentifiers[this.kbdtype][event.originalEvent.keyIdentifier]) {
        if (event.originalEvent.shiftKey) {
          if (!(keyname = keynames[1])) {
            return;
          }
          scCode = "04";
        } else {
          keyname = keynames[0];
          scCode = "00";
        }
        for (i = _i = 0, _ref4 = keys.length; 0 <= _ref4 ? _i < _ref4 : _i > _ref4; i = 0 <= _ref4 ? ++_i : --_i) {
          if (keys[i] && (keyname === keys[i][0] || keyname === keys[i][1])) {
            scanCode = i;
            break;
          }
        }
        if (scanCode) {
          scCode += i;
          if (event.originalEvent.shiftKey) {
            this.$(".origin").html("<span>Shift</span>+<span>" + keyname + "</span>");
          } else {
            this.$(".origin").html("<span>" + keyname + "</span>");
          }
          this.model.set("origin", scCode);
          this.setDesc();
          return this.trigger("resizeInput");
        }
      }
    },
    onClickCopySC: function(event) {
      var body, command, desc, keyCombo, method, scCode, text;
      if (this.model.get("mode") === "remap") {
        method = "keydown";
        scCode = this.model.get("origin");
        desc = this.$(".desc").find(".content,.memo").text();
      } else {
        method = "send";
        scCode = this.model.id;
        desc = this.$(".desc").find(".content,.command,.commandCaption,.bookmark,.memo").text();
      }
      command = this.$("td.options .mode").text().replace("Remap", "");
      if (command) {
        command = " " + command + ":";
      }
      keyCombo = (decodeKbdEvent(scCode)).replace(/\s/g, "");
      if (desc) {
        desc = " " + desc;
      }
      body = "tsc." + method + "('" + (transKbdEvent(scCode)) + "');";
      text = body + " /* " + keyCombo + command + desc + " */";
      return chrome.runtime.sendMessage({
        action: "setClipboard",
        value1: text
      }, function(msg) {});
    },
    onClickCtxMenu: function() {
      var desc;
      if (this.model.get("mode") === "remap") {
        desc = this.$(".desc").find(".content,.memo").text();
      } else {
        desc = this.$(".desc").find(".content,.command,.commandCaption,.bookmark,.memo").text();
      }
      return this.trigger("showPopup", "ctxMenuOptions", this.model, {
        desc: $.trim(desc)
      });
    },
    onClickInputMemo: function() {
      return event.stopPropagation();
    },
    onSubmitMemo: function() {
      this.$("form.memo").hide();
      this.model.set({
        "memo": this.$("div.memo").show().html(escape(this.$("input.memo").val())).text()
      });
      endEdit();
      return false;
    },
    onClickMode: function(event) {
      if (event.currentTarget.getAttribute("title") === "Pause") {
        return;
      }
      if (this.$(".selectMode").toggle().is(":visible")) {
        this.$(".selectMode").focus();
        this.$(".mode").addClass("selecting");
      } else {
        this.$(".mode").removeClass("selecting");
      }
      return event.stopPropagation();
    },
    onChangeMode: function(event, mode) {
      if (event) {
        this.$(".mode").removeClass("selecting");
        mode = event.currentTarget.className;
        this.$(".selectMode").hide();
        if (mode === "bookmark" || mode === "command") {
          this.trigger("showPopup", mode, this.model, this.model.get(mode));
          return;
        }
      }
      this.model.set("mode", mode);
      this.setDispMode(mode);
      this.setDesc();
      return this.trigger("resizeInput");
    },
    onBlurSelectMode: function() {
      this.$(".selectMode").hide();
      return this.$(".mode").removeClass("selecting");
    },
    onFocusKeyInput: function() {
      return lastFocused = this.el;
    },
    onClickInput: function(event, selector) {
      if (event) {
        $(event.currentTarget).focus();
      } else if (selector) {
        this.$(selector).focus();
      } else {
        this.$(".origin").focus();
      }
      return event != null ? event.stopPropagation() : void 0;
    },
    onBlurInputMemo: function() {
      return this.onSubmitMemo();
    },
    onClickCog: function(event) {
      if (this.$(".selectCog").toggle().is(":visible")) {
        this.$(".selectCog").focus();
        $(event.currentTarget).addClass("selecting");
      } else {
        $(event.currentTarget).removeClass("selecting");
      }
      return event.stopPropagation();
    },
    onBlurSelectCog: function() {
      this.$(".selectCog").hide();
      return this.$("button.cog").removeClass("selecting");
    },
    onClickEdit: function(event) {
      var editing, input$, memo, mode, pause;
      if ((mode = this.model.get("mode")) === "through") {
        pause = true;
        mode = this.model.get("lastMode");
      }
      switch (mode) {
        case "bookmark":
          return this.trigger("showPopup", "bookmarkOptions", this.model, this.model.get("bookmark"));
        case "command":
          return this.trigger("showPopup", "commandOptions", this.model, this.model.get("command"));
        default:
          (memo = this.$("div.memo")).toggle();
          editing = (input$ = this.$("form.memo").toggle().find("input.memo")).is(":visible");
          if (editing) {
            input$.focus().val(memo.text());
            startEdit();
          } else {
            this.onSubmitMemo();
          }
          return event.stopPropagation();
      }
    },
    onClickPause: function() {
      this.model.set("lastMode", this.model.get("mode"));
      this.onChangeMode(null, "through");
      return ctxMenuOptionsView.pause(this.model.id);
    },
    onClickResume: function() {
      this.onChangeMode(null, this.model.get("lastMode"));
      return ctxMenuOptionsView.resume(this.model.id);
    },
    onClickRemove: function() {
      var shortcut;
      shortcut = decodeKbdEvent(this.model.id);
      if (confirm("Are you sure you want to delete this shortcut?\n\n '" + shortcut + "'")) {
        return this.trigger("removeConfig", this.model);
      }
    },
    setDispMode: function(mode) {
      this.$(".mode").attr("title", modeDisp[mode][0].replace("...", "")).find(".icon")[0].className = "icon " + modeDisp[mode][1];
      if (mode === "through") {
        mode = this.model.get("lastMode") + " through";
      }
      this.$(".new,.origin,.icon-arrow-right").removeClass(this.optionKeys.join(" ")).addClass(mode);
      if (/remap/.test(mode)) {
        this.$("th:first").removeAttr("colspan");
        return this.$("th:eq(1),th:eq(2)").show();
      } else {
        this.$("th:first").attr("colspan", "3");
        return this.$("th:eq(1),th:eq(2)").hide();
      }
    },
    setKbdValue: function(input$, value) {
      var result;
      if (result = decodeKbdEvent(value)) {
        input$.html(_.map(result.split(" + "), function(s) {
          return "<span>" + s + "</span>";
        }).join("+"));
        return true;
      } else {
        return false;
      }
    },
    setDesc: function() {
      var bookmark, command, commandDisp, content, content3row, desc, editOption, help, i, key, keycombo, lang, lines, mode, pause, tdDesc, test, _i, _j, _ref4, _ref5;
      (tdDesc = this.$(".desc")).empty();
      editOption = {
        iconName: "",
        command: ""
      };
      if ((mode = this.model.get("mode")) === "through") {
        pause = true;
        mode = this.model.get("lastMode");
      }
      switch (mode) {
        case "bookmark":
          bookmark = this.model.get("bookmark");
          tdDesc.append(this.tmplBookmark({
            openmode: bmOpenMode[bookmark.openmode],
            url: bookmark.url,
            title: bookmark.title
          }));
          editOption = {
            iconName: "icon-cog",
            command: "Edit bookmark..."
          };
          break;
        case "command":
          desc = (commandDisp = commandsDisp[this.model.get("command").name])[1];
          if (commandDisp[2]) {
            content3row = [];
            command = this.model.get("command");
            lines = command.content.split("\n");
            for (i = _i = 0, _ref4 = lines.length; 0 <= _ref4 ? _i < _ref4 : _i > _ref4; i = 0 <= _ref4 ? ++_i : --_i) {
              if (i > 2) {
                content3row[i - 1] += " ...";
                break;
              } else {
                content3row.push(lines[i].replace(/"/g, "'"));
              }
            }
            tdDesc.append(this.tmplCommandCustom({
              ctg: commandDisp[3],
              desc: desc,
              content3row: content3row.join("\n"),
              caption: command.caption
            }));
            editOption = {
              iconName: "icon-cog",
              command: "Edit command..."
            };
          } else {
            tdDesc.append(this.tmplCommand({
              desc: desc,
              ctg: commandDisp[0].substring(0, 1).toUpperCase() + commandDisp[0].substring(1)
            }));
          }
          break;
        case "remap":
        case "disabled":
          lang = this.kbdtype === "JP" ? "ja" : "en";
          if (mode === "remap") {
            keycombo = this.$(".origin").text();
          } else {
            keycombo = this.$(".new").text();
          }
          keycombo = (keycombo.replace(/\s/g, "")).toUpperCase();
          if (!(help = scHelp[keycombo])) {
            if (/^CTRL\+[2-7]$/.test(keycombo)) {
              help = scHelp["CTRL+1"];
            }
          }
          if (help) {
            for (i = _j = 0, _ref5 = help[lang].length; 0 <= _ref5 ? _j < _ref5 : _j > _ref5; i = 0 <= _ref5 ? ++_j : --_j) {
              test = help[lang][i].match(/(^\w+)\^(.+)/);
              key = RegExp.$1;
              content = RegExp.$2;
              tdDesc.append(this.tmplHelp({
                sectDesc: scHelpSect[key],
                sectKey: key,
                scHelp: content
              })).find(".sectInit").tooltip({
                position: {
                  my: "left+10 top-60"
                }
              });
            }
          }
      }
      if (tdDesc.html() === "") {
        tdDesc.append(this.tmplMemo({
          memo: this.model.get("memo")
        }));
        editOption = {
          iconName: "icon-pencil",
          command: "Edit description"
        };
      }
      tdDesc.append(this.tmplDesc(editOption));
      if (mode === "disabled") {
        this.$(".addKey,.copySC,.seprater.1st,div.ctxmenu").remove();
      }
      if (editOption.iconName === "") {
        tdDesc.find(".edit").remove();
      }
      if (pause) {
        tdDesc.find(".pause").remove();
      } else {
        tdDesc.find(".resume").remove();
      }
      return this.onChangeCtxmenu();
    },
    tmplDesc: _.template("<button class=\"cog small\"><i class=\"icon-caret-down\"></i></button>\n<div class=\"selectCog\" tabIndex=\"0\">\n  <div class=\"edit\"><i class=\"<%=iconName%>\"></i> <%=command%></div>\n  <div class=\"addKey\"><i class=\"icon-plus\"></i> Add KeyEvent</div>\n  <div class=\"ctxmenu\"><i class=\"icon-reorder\"></i> Create context menu...</div>\n  <div class=\"copySC\"><i class=\"icon-paper-clip\"></i> Copy script</div>\n  <span class=\"seprater 1st\"><hr style=\"margin:3px 1px\" noshade></span>\n  <div class=\"pause\"><i class=\"icon-pause\"></i> Pause</div>\n  <div class=\"resume\"><i class=\"icon-play\"></i> Resume</div>\n  <span class=\"seprater\"><hr style=\"margin:3px 1px\" noshade></span>\n  <div class=\"delete\"><i class=\"icon-trash\"></i> Delete</div>\n</div>"),
    tmplMemo: _.template("<form class=\"memo\">\n  <input type=\"text\" class=\"memo\">\n</form>\n<div class=\"memo\"><%=memo%></div>"),
    tmplBookmark: _.template("<div class=\"bookmark\" title=\"<<%=openmode%>>\n<%=url%>\" style=\"background-image:-webkit-image-set(url(chrome://favicon/size/16@1x/<%=url%>) 1x);\"><%=title%></div>"),
    tmplCommand: _.template("<div class=\"ctgIcon <%=ctg%>\"><%=ctg%></div><div class=\"command\"><%=desc%></div>"),
    tmplCommandCustom: _.template("<div class=\"ctgIcon <%=ctg%>\"><%=ctg%></div>\n<div class=\"command\"><%=desc%>:</div><div class=\"commandCaption\" title=\"<%=content3row%>\"><%=caption%></div>"),
    tmplHelp: _.template("<div class=\"sectInit\" title=\"<%=sectDesc%>\"><%=sectKey%></div><div class=\"content\"><%=scHelp%></div>"),
    template: _.template("<tr class=\"data\">\n  <th>\n    <div class=\"new\" tabIndex=\"0\"></div>\n  </th>\n  <th>\n    <i class=\"icon-arrow-right\"></i>\n  </th>\n  <th class=\"tdOrigin\">\n    <div class=\"origin\" tabIndex=\"-1\"></div>\n  </th>\n  <td class=\"options\">\n    <div class=\"mode\"><i class=\"icon\"></i><span></span><i class=\"icon-caret-down\"></i></div>\n    <div class=\"selectMode\" tabIndex=\"0\">\n      <% _.each(options, function(option, key) { if (option[2] != \"nodisp\") { %>\n      <div class=\"<%=key%>\"><i class=\"icon <%=option[1]%>\"></i> <%=option[0]%></div>\n      <% }}); %>\n    </div>\n  <td class=\"ctxmenu\"></td>\n  <td class=\"desc\"></td>\n  <td class=\"blank\">&nbsp;</td>\n</tr>")
  });

  KeyConfigSetView = Backbone.View.extend({
    placeholder: "Enter new shortcut key",
    el: "table.keyConfigSetView",
    events: {
      "click .addnew": "onClickAddnew",
      "blur  .addnew": "onBlurAddnew",
      "click": "onClickBlank"
    },
    initialize: function(options) {
      this.collection.comparator = function(model) {
        return model.get("ordernum");
      };
      return this.collection.on({
        add: this.onAddRender,
        kbdEvent: this.onKbdEvent
      }, this);
    },
    render: function(keyConfigSet) {
      var _this = this;
      this.$el.append(this.template());
      this.collection.set(keyConfigSet);
      this.$("tbody").sortable({
        delay: 300,
        scroll: true,
        cursor: "move",
        update: function() {
          return _this.onUpdateSort();
        },
        start: function() {
          return _this.onStartSort();
        },
        stop: function() {
          return _this.onStopSort();
        }
      });
      $(".fixed-table-container-inner").niceScroll({
        cursorwidth: 12,
        cursorborderradius: 2,
        smoothscroll: true,
        cursoropacitymin: .3,
        cursoropacitymax: .7,
        zindex: 999998
      });
      this.niceScroll = $(".fixed-table-container-inner").getNiceScroll();
      return this;
    },
    onAddRender: function(model) {
      var divAddNew, keyConfigView, tbody;
      keyConfigView = new KeyConfigView({
        model: model
      });
      keyConfigView.on("removeConfig", this.onChildRemoveConfig, this);
      keyConfigView.on("resizeInput", this.onChildResizeInput, this);
      keyConfigView.on("showPopup", this.onShowPopup, this);
      divAddNew = this.$("tr.addnew")[0] || null;
      tbody = this.$("tbody")[0];
      tbody.insertBefore(keyConfigView.render(this.model.get("kbdtype")).el, divAddNew);
      tbody.insertBefore($(this.tmplBorder)[0], divAddNew);
      if (divAddNew) {
        this.$("div.addnew").blur();
        this.onUpdateSort();
      }
      if (keyConfigView.state === "invalid") {
        return this.onChildRemoveConfig(model);
      }
    },
    onKbdEvent: function(value) {
      var model, newitem, originValue, target;
      if (this.$(".addnew").length === 0) {
        if ((target = this.$(".new:focus,.origin:focus")).length === 0) {
          if (model = this.collection.get(value)) {
            model.trigger("setFocus", null, ".new");
            return;
          } else {
            if (!this.onClickAddKeyConfig()) {
              return;
            }
          }
        } else {
          return;
        }
      }
      if (this.collection.findWhere({
        "new": value
      })) {
        $("#tiptip_content").text("\"" + (decodeKbdEvent(value)) + "\" is already exists.");
        this.$("div.addnew").tipTip();
        return;
      }
      if (~~value.substring(2) > 0x200) {
        originValue = "0130";
      } else {
        originValue = value;
      }
      this.collection.add(newitem = new KeyConfig({
        "new": value,
        origin: originValue
      }));
      this.$("tbody").sortable("enable").sortable("refresh");
      windowOnResize();
      this.onChildResizeInput();
      return newitem.trigger("setFocus");
    },
    onChildRemoveConfig: function(model) {
      this.collection.remove(model);
      this.onStopSort();
      windowOnResize();
      return this.onChildResizeInput();
    },
    onChildResizeInput: function() {
      var _this = this;
      this.$(".th_inner").css("left", 0);
      return setTimeout((function() {
        return _this.$(".th_inner").css("left", "");
      }), 0);
    },
    onShowPopup: function(name, model, options) {
      return this.trigger("showPopup", name, model, options);
    },
    onGetCtxMenuParents: function(container) {
      var parents;
      parents = [];
      this.collection.models.forEach(function(model) {
        var ctxMenu, parent;
        if (ctxMenu = model.get("ctxMenu")) {
          if ((parent = ctxMenu.parent) !== "root") {
            return parents.push(parent);
          }
        }
      });
      return container.parents = _.unique(parents);
    },
    onRemakeCtxMenu: function(container) {
      return andy.remakeCtxMenu(this.getSaveData()).done(function() {
        return container.dfd.resolve();
      });
    },
    onGetCtxMenues: function(container) {
      var key, menuParents;
      container.ctxMenus = [];
      menuParents = {};
      this.collection.models.forEach(function(model) {
        var ctxMenu;
        if (ctxMenu = model.get("ctxMenu")) {
          container.ctxMenus.push({
            id: model.id,
            caption: ctxMenu.caption,
            contexts: ctxMenu.contexts,
            parent: ctxMenu.parent,
            order: ctxMenu.order || 999
          });
          return menuParents[ctxMenu.parent] = ctxMenu.parentOrder || 999;
        }
      });
      container.parents = [];
      for (key in menuParents) {
        container.parents.push({
          id: key,
          order: menuParents[key]
        });
      }
      container.ctxMenus.sort(function(a, b) {
        return a.order - b.order;
      });
      return container.parents.sort(function(a, b) {
        return a.order - b.order;
      });
    },
    onClickAddKeyConfig: function(event) {
      var newItem$;
      if (this.$(".addnew").length > 0) {
        return;
      }
      if (this.collection.length > gMaxItems) {
        $("#tiptip_content").text("You have reached the maximum number of items. (Max " + gMaxItems + " items)");
        $(event.currentTarget).tipTip({
          defaultPosition: "left"
        });
        return false;
      }
      newItem$ = $(this.tmplAddNew({
        placeholder: this.placeholder
      }));
      this.$("tbody")[0].insertBefore(newItem$[0], lastFocused);
      newItem$.find(".addnew").focus()[0].scrollIntoViewIfNeeded();
      this.$("tbody").sortable("disable");
      return windowOnResize();
    },
    onClickBlank: function() {
      this.$(":focus").blur();
      return lastFocused = null;
    },
    onClickAddnew: function(event) {
      return event.stopPropagation();
    },
    onBlurAddnew: function() {
      this.$(".addnew").remove();
      this.$("tbody").sortable("enable");
      return windowOnResize();
    },
    onChangeSelKbd: function(event) {
      var newKbd;
      keys = keyCodes[newKbd = event.currentTarget.value].keys;
      this.collection.trigger("changeKbd", newKbd);
      return this.model.set("kbdtype", newKbd);
    },
    onStartSort: function() {
      return this.$(".ui-sortable-placeholder").next("tr.border").remove();
    },
    onStopSort: function() {
      var target$,
        _this = this;
      $.each(this.$("tbody tr"), function(i, tr) {
        var target$, _ref4, _ref5;
        if (tr.className === "data") {
          if (((_ref4 = $(tr).next("tr")[0]) != null ? _ref4.className : void 0) !== "border") {
            return $(tr).after(_this.tmplBorder);
          }
        } else {
          if (((_ref5 = (target$ = $(tr).next("tr"))[0]) != null ? _ref5.className : void 0) !== "data") {
            return target$.remove();
          }
        }
      });
      if ((target$ = this.$("tbody tr:first"))[0].className === "border") {
        return target$.remove();
      }
    },
    onUpdateSort: function() {
      this.collection.trigger("updateOrder");
      return this.collection.sort();
    },
    getSaveData: function() {
      this.collection.remove(this.collection.findWhere({
        "new": this.placeholder
      }));
      return {
        config: this.model.toJSON(),
        keyConfigSet: this.collection.toJSON()
      };
    },
    tmplAddNew: _.template("<tr class=\"addnew\">\n  <th colspan=\"3\">\n    <div class=\"new addnew\" tabIndex=\"0\"><%=placeholder%></div>\n  </th>\n  <td></td><td></td><td></td><td class=\"blank\"></td>\n</tr>"),
    tmplBorder: "<tr class=\"border\">\n  <td colspan=\"6\"><div class=\"border\"></div></td>\n  <td></td>\n</tr>",
    template: _.template("<thead>\n  <tr>\n    <th>\n      <div class=\"th_inner\">New <i class=\"icon-arrow-right\"></i> Origin shortcut key</div>\n    </th>\n    <th></th>\n    <th></th>\n    <th>\n      <div class=\"th_inner options\">Mode</div>\n    </th>\n    <th class=\"ctxmenu\"></th>\n    <th>\n      <div class=\"th_inner desc\">Description</div>\n    </th>\n    <th><div class=\"th_inner blank\">&nbsp;</div></th>\n  </tr>\n</thead>\n<tbody></tbody>")
  });

  marginBottom = 0;

  resizeTimer = false;

  windowOnResize = function() {
    if (resizeTimer) {
      clearTimeout(resizeTimer);
    }
    return resizeTimer = setTimeout((function() {
      var tableHeight;
      tableHeight = window.innerHeight - document.querySelector(".header").offsetHeight - marginBottom;
      document.querySelector(".fixed-table-container").style.pixelHeight = tableHeight;
      $(".fixed-table-container-inner").getNiceScroll().resize();
      return $(".result_outer").getNiceScroll().resize();
    }), 200);
  };

  startEdit = function() {
    return andy.startEdit();
  };

  endEdit = function() {
    return andy.endEdit();
  };

  andy = chrome.extension.getBackgroundPage().andy;

  $ = jQuery;

  $(function() {
    var bookmarkOptionsView, ctxMenuManagerView, headerView, saveData;
    keyCodes = andy.getKeyCodes();
    scHelp = andy.getScHelp();
    scHelpSect = andy.getScHelpSect();
    saveData = andy.local;
    headerView = new HeaderView({
      model: new Config(saveData.config)
    });
    headerView.render();
    keyConfigSetView = new KeyConfigSetView({
      model: new Config(saveData.config),
      collection: new KeyConfigSet()
    });
    keyConfigSetView.render(saveData.keyConfigSet);
    bookmarksView = new BookmarksView({});
    bookmarkOptionsView = new BookmarkOptionsView({});
    commandsView = new CommandsView({});
    commandOptionsView = new CommandOptionsView({});
    ctxMenuOptionsView = new CtxMenuOptionsView({});
    ctxMenuManagerView = new CtxMenuManagerView({});
    headerView.on("clickAddKeyConfig", keyConfigSetView.onClickAddKeyConfig, keyConfigSetView);
    headerView.on("changeSelKbd", keyConfigSetView.onChangeSelKbd, keyConfigSetView);
    ctxMenuOptionsView.on("getCtxMenuParents", keyConfigSetView.onGetCtxMenuParents, keyConfigSetView);
    ctxMenuOptionsView.on("remakeCtxMenu", keyConfigSetView.onRemakeCtxMenu, keyConfigSetView);
    ctxMenuManagerView.on("getCtxMenues", keyConfigSetView.onGetCtxMenues, keyConfigSetView);
    chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
      switch (request.action) {
        case "kbdEvent":
          return keyConfigSetView.collection.trigger("kbdEvent", request.value);
        case "saveConfig":
          return andy.saveConfig(keyConfigSetView.getSaveData());
      }
    });
    $(window).on("unload", function() {
      return andy.saveConfig(keyConfigSetView.getSaveData());
    }).on("resize", function() {
      return windowOnResize();
    }).on("click", function() {
      return lastFocused = null;
    });
    return windowOnResize();
  });

}).call(this);
